import type {
  AdminStats,
  AdminBooking,
  AdminVerification,
  AdminJobRequest,
  AdminVerificationDetail,
  AdminDispute,
  AdminDisputeDetail,
  AdminBookingDetail,
  AdminJobRequestDetail,
} from "@/lib/types"

export const adminStats: AdminStats = {
  totalUsers: 2847,
  totalProviders: 412,
  totalListings: 1893,
  totalJobRequests: 3421,
  totalBookings: 8934,
  paidGmv: 847320,
  platformRevenue: 101678,
}

export const recentBookings: AdminBooking[] = [
  {
    id: "booking-1",
    jobTitle: "Elektroinstallation Küche",
    customerName: "Anna Schmidt",
    providerName: "Elektro Meier GmbH",
    status: "confirmed",
    amount: 450,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "booking-2",
    jobTitle: "Badezimmer Renovierung",
    customerName: "Thomas Müller",
    providerName: "Sanitär Weber",
    status: "in_progress",
    amount: 2800,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "booking-3",
    jobTitle: "Wohnzimmer streichen",
    customerName: "Lisa Bauer",
    providerName: "Maler König",
    status: "pending",
    amount: 680,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: "booking-4",
    jobTitle: "Trockenbau Dachgeschoss",
    customerName: "Michael Wagner",
    providerName: "Bau & Ausbau Berlin",
    status: "completed",
    amount: 3200,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: "booking-5",
    jobTitle: "Steckdosen Installation",
    customerName: "Sandra Fischer",
    providerName: "Elektro Express",
    status: "disputed",
    amount: 320,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
  },
  {
    id: "booking-8",
    jobTitle: "Badezimmer Fliesen",
    customerName: "Martin Schulz",
    providerName: "Fliesen Meister GmbH",
    status: "disputed",
    amount: 1450,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
  {
    id: "booking-20",
    jobTitle: "Heizung Wartung",
    customerName: "Anna Meier",
    providerName: "Heizung & Sanitär Schmidt",
    status: "disputed",
    amount: 420,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
]

export const pendingVerifications: AdminVerification[] = [
  {
    id: "ver-1",
    providerName: "Hans Schneider",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    companyName: "Schneider Elektrotechnik",
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    documentCount: 3,
    status: "pending",
  },
  {
    id: "ver-2",
    providerName: "Maria Hoffmann",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    companyName: "Hoffmann Sanitär",
    submittedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    documentCount: 3,
    status: "pending",
  },
  {
    id: "ver-3",
    providerName: "Klaus Richter",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    companyName: "Richter Malerbetrieb",
    submittedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    documentCount: 2,
    status: "pending",
  },
  {
    id: "ver-4",
    providerName: "Julia Braun",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    companyName: "Braun Trockenbau",
    submittedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    documentCount: 3,
    status: "pending",
  },
]

export const recentJobRequests: AdminJobRequest[] = [
  {
    id: "jr-1",
    title: "Küche komplett renovieren",
    customerName: "Peter Klein",
    category: "Trockenbau",
    status: "open",
    offerCount: 0,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: "jr-2",
    title: "Lampen installieren",
    customerName: "Eva Schulz",
    category: "Elektriker",
    status: "in_discussion",
    offerCount: 4,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: "jr-3",
    title: "Wasserhahn austauschen",
    customerName: "Frank Weber",
    category: "Sanitär",
    status: "open",
    offerCount: 2,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "jr-4",
    title: "Flur und Treppenhaus streichen",
    customerName: "Gabi Meyer",
    category: "Maler",
    status: "filled",
    offerCount: 6,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    id: "jr-5",
    title: "Rigipswand einziehen",
    customerName: "Heinz Wolf",
    category: "Trockenbau",
    status: "open",
    offerCount: 1,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
]

export const verificationQueue: AdminVerificationDetail[] = [
  {
    id: "ver-1",
    providerName: "Hans Schneider",
    providerAvatar: "/placeholder.svg?height=80&width=80",
    providerEmail: "hans.schneider@elektrotechnik.de",
    companyName: "Schneider Elektrotechnik",
    vatId: "DE123456789",
    city: "Berlin",
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    status: "pending",
    documents: [
      {
        id: "doc-1",
        type: "id",
        fileName: "personalausweis.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: "doc-2",
        type: "trade_license",
        fileName: "handwerkskarte.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: "doc-3",
        type: "insurance",
        fileName: "haftpflicht_2024.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "ver-2",
    providerName: "Maria Hoffmann",
    providerAvatar: "/placeholder.svg?height=80&width=80",
    providerEmail: "maria@hoffmann-sanitaer.de",
    companyName: "Hoffmann Sanitär",
    vatId: "DE987654321",
    city: "Hamburg",
    submittedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    status: "pending",
    documents: [
      {
        id: "doc-4",
        type: "id",
        fileName: "ausweis_hoffmann.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        id: "doc-5",
        type: "trade_license",
        fileName: "meisterbrief.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
      {
        id: "doc-6",
        type: "insurance",
        fileName: "versicherung.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "ver-3",
    providerName: "Klaus Richter",
    providerAvatar: "/placeholder.svg?height=80&width=80",
    providerEmail: "info@richter-maler.de",
    companyName: "Richter Malerbetrieb",
    city: "München",
    submittedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    status: "pending",
    documents: [
      {
        id: "doc-7",
        type: "id",
        fileName: "id_richter.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
      {
        id: "doc-8",
        type: "trade_license",
        fileName: "gewerbeschein.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "ver-4",
    providerName: "Julia Braun",
    providerAvatar: "/placeholder.svg?height=80&width=80",
    providerEmail: "julia@braun-trockenbau.de",
    companyName: "Braun Trockenbau",
    vatId: "DE456789123",
    city: "Köln",
    submittedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    status: "pending",
    documents: [
      {
        id: "doc-9",
        type: "id",
        fileName: "ausweis_braun.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },
      {
        id: "doc-10",
        type: "trade_license",
        fileName: "handwerkskammer.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },
      {
        id: "doc-11",
        type: "insurance",
        fileName: "betriebshaftpflicht.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "ver-5",
    providerName: "Stefan Weber",
    providerAvatar: "/placeholder.svg?height=80&width=80",
    providerEmail: "stefan@weber-bau.de",
    companyName: "Weber Bauservice",
    vatId: "DE111222333",
    city: "Berlin",
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    status: "approved",
    documents: [
      {
        id: "doc-12",
        type: "id",
        fileName: "personalausweis_weber.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
      {
        id: "doc-13",
        type: "trade_license",
        fileName: "meisterbrief_weber.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
      {
        id: "doc-14",
        type: "insurance",
        fileName: "haftpflicht_weber.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
    ],
    reviewedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    reviewedBy: "Admin Team",
  },
  {
    id: "ver-6",
    providerName: "Thomas Krüger",
    providerAvatar: "/placeholder.svg?height=80&width=80",
    providerEmail: "tk@krueger-elektro.de",
    companyName: "Krüger Elektro",
    city: "Frankfurt",
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    status: "rejected",
    documents: [
      {
        id: "doc-15",
        type: "id",
        fileName: "ausweis_krueger.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
      {
        id: "doc-16",
        type: "trade_license",
        fileName: "lizenz_abgelaufen.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
    ],
    adminNotes: "Handwerkskarte ist abgelaufen (Gültigkeit bis 2023). Bitte aktuelles Dokument einreichen.",
    reviewedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    reviewedBy: "Admin Team",
  },
  {
    id: "ver-7",
    providerName: "Anna Müller",
    providerAvatar: "/placeholder.svg?height=80&width=80",
    providerEmail: "anna@mueller-sanitaer.de",
    companyName: "Müller Sanitärtechnik",
    vatId: "DE333444555",
    city: "Hamburg",
    submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    status: "approved",
    documents: [
      {
        id: "doc-17",
        type: "id",
        fileName: "id_mueller.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
      {
        id: "doc-18",
        type: "trade_license",
        fileName: "gesellenbrief.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
      {
        id: "doc-19",
        type: "insurance",
        fileName: "versicherung_mueller.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
    ],
    reviewedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    reviewedBy: "Admin Team",
  },
  {
    id: "ver-8",
    providerName: "Michael Becker",
    providerAvatar: "/placeholder.svg?height=80&width=80",
    providerEmail: "m.becker@becker-maler.de",
    companyName: "Becker Malerarbeiten",
    city: "Düsseldorf",
    submittedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: "rejected",
    documents: [
      {
        id: "doc-20",
        type: "id",
        fileName: "ausweis_becker.pdf",
        fileUrl: "#",
        uploadedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      },
    ],
    adminNotes: "Unvollständige Unterlagen: Handwerkskarte/Gewerbeschein und Versicherungsnachweis fehlen.",
    reviewedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    reviewedBy: "Admin Team",
  },
]

export const adminDisputes: AdminDispute[] = [
  {
    id: "dispute-1",
    bookingId: "booking-5",
    bookingTitle: "Steckdosen Installation",
    openedBy: "customer",
    openerName: "Sandra Fischer",
    reason: "quality",
    reasonDetails: "Die Installation wurde nicht fachgerecht durchgeführt.",
    status: "open",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    customerName: "Sandra Fischer",
    providerName: "Elektro Express",
    bookingAmount: 320,
  },
  {
    id: "dispute-2",
    bookingId: "booking-8",
    bookingTitle: "Badezimmer Fliesen",
    openedBy: "customer",
    openerName: "Martin Schulz",
    reason: "no_show",
    reasonDetails: "Handwerker ist zum vereinbarten Termin nicht erschienen.",
    status: "under_review",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    customerName: "Martin Schulz",
    providerName: "Fliesen Meister GmbH",
    bookingAmount: 1450,
  },
  {
    id: "dispute-3",
    bookingId: "booking-12",
    bookingTitle: "Wasserleck Reparatur",
    openedBy: "provider",
    openerName: "Sanitär Weber",
    reason: "payment",
    reasonDetails: "Kunde verweigert Zahlung trotz abgeschlossener Arbeit.",
    status: "escalated",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    customerName: "Peter Hoffmann",
    providerName: "Sanitär Weber",
    bookingAmount: 890,
  },
  {
    id: "dispute-4",
    bookingId: "booking-15",
    bookingTitle: "Wohnzimmer streichen",
    openedBy: "customer",
    openerName: "Julia Braun",
    reason: "damage",
    reasonDetails: "Beim Streichen wurde der Holzboden beschädigt.",
    status: "under_review",
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
    customerName: "Julia Braun",
    providerName: "Maler König",
    bookingAmount: 580,
  },
  {
    id: "dispute-5",
    bookingId: "booking-18",
    bookingTitle: "Elektrik Altbau",
    openedBy: "customer",
    openerName: "Klaus Werner",
    reason: "communication",
    reasonDetails: "Keine Rückmeldung auf mehrere Nachrichten nach Anzahlung.",
    status: "open",
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
    customerName: "Klaus Werner",
    providerName: "Elektro Blitz",
    bookingAmount: 2100,
  },
  {
    id: "dispute-6",
    bookingId: "booking-20",
    bookingTitle: "Heizung Wartung",
    openedBy: "customer",
    openerName: "Anna Meier",
    reason: "quality",
    reasonDetails: "Problem besteht weiterhin nach der Reparatur.",
    status: "resolved",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    customerName: "Anna Meier",
    providerName: "Heizung & Sanitär Schmidt",
    bookingAmount: 420,
  },
  {
    id: "dispute-7",
    bookingId: "booking-22",
    bookingTitle: "Küche Montage",
    openedBy: "provider",
    openerName: "Möbel Montage Pro",
    reason: "other",
    reasonDetails: "Kunde hat zusätzliche Arbeiten verlangt ohne Bezahlung.",
    status: "resolved",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    customerName: "Stefan Wolf",
    providerName: "Möbel Montage Pro",
    bookingAmount: 750,
  },
]

export const disputeDetails: Record<string, AdminDisputeDetail> = {
  "dispute-1": {
    id: "dispute-1",
    bookingId: "booking-5",
    bookingTitle: "Steckdosen Installation",
    openedBy: "customer",
    openerName: "Sandra Fischer",
    reason: "quality",
    reasonDetails:
      "Die Installation wurde nicht fachgerecht durchgeführt. Es gibt Probleme mit der Verkabelung und eine Steckdose funktioniert nicht.",
    status: "open",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    customerName: "Sandra Fischer",
    providerName: "Elektro Express",
    bookingAmount: 320,
    booking: {
      id: "booking-5",
      jobTitle: "Steckdosen Installation",
      category: "Elektriker",
      scheduledDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      completedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      amount: 320,
      customerName: "Sandra Fischer",
      customerAvatar: "/placeholder.svg?height=40&width=40",
      providerName: "Elektro Express",
      providerAvatar: "/placeholder.svg?height=40&width=40",
    },
    messages: [
      {
        id: "msg-1",
        senderName: "Sandra Fischer",
        senderRole: "customer",
        content: "Die Arbeit wurde nicht richtig ausgeführt. Eine Steckdose funktioniert überhaupt nicht.",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: "msg-2",
        senderName: "Elektro Express",
        senderRole: "provider",
        content: "Die Installation wurde nach Vorschrift durchgeführt. Ich kann gerne nochmal vorbeikommen.",
        timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
      },
    ],
  },
  "dispute-2": {
    id: "dispute-2",
    bookingId: "booking-8",
    bookingTitle: "Badezimmer Fliesen",
    openedBy: "customer",
    openerName: "Martin Schulz",
    reason: "no_show",
    reasonDetails: "Handwerker ist zum vereinbarten Termin nicht erschienen und hat sich nicht gemeldet.",
    status: "under_review",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    customerName: "Martin Schulz",
    providerName: "Fliesen Meister GmbH",
    bookingAmount: 1450,
    booking: {
      id: "booking-8",
      jobTitle: "Badezimmer Fliesen",
      category: "Fliesenleger",
      scheduledDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      amount: 1450,
      customerName: "Martin Schulz",
      customerAvatar: "/placeholder.svg?height=40&width=40",
      providerName: "Fliesen Meister GmbH",
      providerAvatar: "/placeholder.svg?height=40&width=40",
    },
    messages: [
      {
        id: "msg-3",
        senderName: "Martin Schulz",
        senderRole: "customer",
        content: "Ich habe den ganzen Tag gewartet, aber niemand ist gekommen.",
        timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
      },
    ],
  },
  "dispute-6": {
    id: "dispute-6",
    bookingId: "booking-20",
    bookingTitle: "Heizung Wartung",
    openedBy: "customer",
    openerName: "Anna Meier",
    reason: "quality",
    reasonDetails: "Problem besteht weiterhin nach der Reparatur.",
    status: "resolved",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    customerName: "Anna Meier",
    providerName: "Heizung & Sanitär Schmidt",
    bookingAmount: 420,
    booking: {
      id: "booking-20",
      jobTitle: "Heizung Wartung",
      category: "Sanitär",
      scheduledDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
      completedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      amount: 420,
      customerName: "Anna Meier",
      customerAvatar: "/placeholder.svg?height=40&width=40",
      providerName: "Heizung & Sanitär Schmidt",
      providerAvatar: "/placeholder.svg?height=40&width=40",
    },
    messages: [
      {
        id: "msg-4",
        senderName: "Anna Meier",
        senderRole: "customer",
        content: "Die Heizung macht immer noch Geräusche.",
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
      {
        id: "msg-5",
        senderName: "Admin Team",
        senderRole: "admin",
        content: "Wir haben den Fall geprüft. Der Anbieter wird die Reparatur kostenlos wiederholen.",
        timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      },
    ],
    resolution: {
      type: "no_refund",
      notes: "Anbieter hat zugestimmt, die Reparatur kostenlos zu wiederholen. Kunde ist einverstanden.",
      resolvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      resolvedBy: "Admin Team",
    },
  },
}

export const adminBookingsData: AdminBookingDetail[] = [
  {
    id: "BK-2024-001",
    jobTitle: "Elektroinstallation Küche",
    description: "Installation von 4 neuen Steckdosen und Anschluss für Herd und Geschirrspüler in der Küche.",
    category: "Elektriker",
    status: "scheduled",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    scheduledTime: "09:00",
    subtotal: 450,
    platformFee: 54,
    total: 504,
    providerPayout: 396,
    paymentStatus: "paid",
    address: {
      street: "Hauptstraße",
      houseNumber: "42",
      plz: "10115",
      city: "Berlin",
    },
    customer: {
      id: "cust-1",
      name: "Anna Schmidt",
      email: "anna.schmidt@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
      phone: "+49 170 1234567",
    },
    provider: {
      id: "prov-1",
      name: "Elektro Meier",
      email: "kontakt@elektro-meier.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Elektro Meier GmbH",
      verified: true,
      phone: "+49 30 9876543",
    },
    recentMessages: [
      {
        id: "msg-1",
        senderName: "Anna Schmidt",
        senderRole: "customer",
        content: "Können wir den Termin um 9 Uhr machen?",
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        id: "msg-2",
        senderName: "Elektro Meier",
        senderRole: "provider",
        content: "Ja, 9 Uhr passt perfekt. Bis dann!",
        timestamp: new Date(Date.now() - 23 * 60 * 60 * 1000),
      },
    ],
    accessNotes: "Schlüssel beim Nachbarn (Müller, 2. Stock)",
  },
  {
    id: "BK-2024-002",
    jobTitle: "Badezimmer Renovierung",
    description: "Komplette Renovierung des Badezimmers inkl. neuer Fliesen, Sanitäranlagen und Dusche.",
    category: "Sanitär",
    status: "in_progress",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    scheduledTime: "08:00",
    subtotal: 2800,
    platformFee: 336,
    total: 3136,
    providerPayout: 2464,
    paymentStatus: "paid",
    address: {
      street: "Berliner Allee",
      houseNumber: "15a",
      plz: "20095",
      city: "Hamburg",
    },
    customer: {
      id: "cust-2",
      name: "Thomas Müller",
      email: "t.mueller@mail.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-2",
      name: "Sanitär Weber",
      email: "info@sanitaer-weber.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Weber Sanitär & Heizung",
      verified: true,
    },
    recentMessages: [
      {
        id: "msg-3",
        senderName: "Sanitär Weber",
        senderRole: "provider",
        content: "Die Fliesen sind heute angekommen. Morgen geht es weiter.",
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "BK-2024-003",
    jobTitle: "Wohnzimmer streichen",
    description: "Streichen aller Wände und Decke im Wohnzimmer (ca. 35 qm). Farbe: Weiß matt.",
    category: "Maler",
    status: "requested",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    subtotal: 680,
    platformFee: 81.6,
    total: 761.6,
    providerPayout: 598.4,
    paymentStatus: "pending",
    address: {
      street: "Schillerstraße",
      houseNumber: "8",
      plz: "80336",
      city: "München",
    },
    customer: {
      id: "cust-3",
      name: "Lisa Bauer",
      email: "lisa.bauer@gmail.com",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-3",
      name: "Maler König",
      email: "anfrage@maler-koenig.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Maler König",
      verified: true,
    },
    recentMessages: [],
  },
  {
    id: "BK-2024-004",
    jobTitle: "Trockenbau Dachgeschoss",
    description: "Ausbau des Dachgeschosses mit Rigipswänden, inkl. Dämmung und Spachteln.",
    category: "Trockenbau",
    status: "completed",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    scheduledTime: "07:30",
    completedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    subtotal: 3200,
    platformFee: 384,
    total: 3584,
    providerPayout: 2816,
    paymentStatus: "paid",
    address: {
      street: "Königsallee",
      houseNumber: "120",
      plz: "40212",
      city: "Düsseldorf",
    },
    customer: {
      id: "cust-4",
      name: "Michael Wagner",
      email: "m.wagner@web.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-4",
      name: "Bau & Ausbau Berlin",
      email: "kontakt@bauausbau-berlin.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Bau & Ausbau Berlin GmbH",
      verified: true,
    },
    recentMessages: [
      {
        id: "msg-4",
        senderName: "Michael Wagner",
        senderRole: "customer",
        content: "Super Arbeit! Vielen Dank!",
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "BK-2024-005",
    jobTitle: "Steckdosen Installation",
    description: "Installation von 3 Steckdosen im Arbeitszimmer.",
    category: "Elektriker",
    status: "disputed",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    scheduledTime: "14:00",
    completedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    subtotal: 320,
    platformFee: 38.4,
    total: 358.4,
    providerPayout: 281.6,
    paymentStatus: "paid",
    address: {
      street: "Friedrichstraße",
      houseNumber: "55",
      plz: "10117",
      city: "Berlin",
    },
    customer: {
      id: "cust-5",
      name: "Sandra Fischer",
      email: "s.fischer@outlook.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-5",
      name: "Elektro Express",
      email: "service@elektro-express.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Elektro Express",
      verified: false,
    },
    recentMessages: [
      {
        id: "msg-5",
        senderName: "Sandra Fischer",
        senderRole: "customer",
        content: "Eine der Steckdosen funktioniert nicht richtig.",
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
    ],
    adminNotes: "Streitfall eröffnet: Qualitätsmangel gemeldet.",
  },
  {
    id: "BK-2024-006",
    jobTitle: "Wasserhahn austauschen",
    description: "Austausch des Küchenwasserhahns gegen ein neues Modell (vom Kunden bereitgestellt).",
    category: "Sanitär",
    status: "needs_payment",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    scheduledTime: "11:00",
    subtotal: 120,
    platformFee: 14.4,
    total: 134.4,
    providerPayout: 105.6,
    paymentStatus: "pending",
    address: {
      street: "Goethestraße",
      houseNumber: "22",
      plz: "50674",
      city: "Köln",
    },
    customer: {
      id: "cust-6",
      name: "Frank Weber",
      email: "frank.weber@mail.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-6",
      name: "Hoffmann Sanitär",
      email: "info@hoffmann-sanitaer.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Hoffmann Sanitär",
      verified: true,
    },
    recentMessages: [],
  },
  {
    id: "BK-2024-007",
    jobTitle: "Lampen montieren",
    description: "Montage von 5 Deckenlampen in Wohnung (Altbau, hohe Decken).",
    category: "Elektriker",
    status: "paid",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    scheduledTime: "10:00",
    subtotal: 250,
    platformFee: 30,
    total: 280,
    providerPayout: 220,
    paymentStatus: "paid",
    address: {
      street: "Prenzlauer Allee",
      houseNumber: "88",
      plz: "10405",
      city: "Berlin",
    },
    customer: {
      id: "cust-7",
      name: "Eva Schulz",
      email: "eva.schulz@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-7",
      name: "Schneider Elektrotechnik",
      email: "info@schneider-elektro.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Schneider Elektrotechnik",
      verified: true,
    },
    recentMessages: [
      {
        id: "msg-6",
        senderName: "Schneider Elektrotechnik",
        senderRole: "provider",
        content: "Ich bringe eine Leiter mit. Bis morgen!",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "BK-2024-008",
    jobTitle: "Flur und Treppenhaus streichen",
    description: "Streichen von Flur und Treppenhaus über 3 Etagen. Farbe wird gestellt.",
    category: "Maler",
    status: "cancelled",
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    scheduledTime: "08:00",
    subtotal: 1200,
    platformFee: 144,
    total: 1344,
    providerPayout: 1056,
    paymentStatus: "refunded",
    address: {
      street: "Maximilianstraße",
      houseNumber: "12",
      plz: "80539",
      city: "München",
    },
    customer: {
      id: "cust-8",
      name: "Gabi Meyer",
      email: "g.meyer@gmx.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-8",
      name: "Richter Malerbetrieb",
      email: "kontakt@richter-maler.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Richter Malerbetrieb",
      verified: true,
    },
    recentMessages: [],
    adminNotes: "Kunde hat aus persönlichen Gründen storniert. Volle Rückerstattung.",
  },
  {
    id: "BK-2024-009",
    jobTitle: "Rigipswand einziehen",
    description: "Neue Trennwand aus Rigips im Wohnzimmer zur Abtrennung eines Arbeitsbereichs.",
    category: "Trockenbau",
    status: "scheduled",
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    scheduledTime: "08:30",
    subtotal: 850,
    platformFee: 102,
    total: 952,
    providerPayout: 748,
    paymentStatus: "paid",
    address: {
      street: "Zeil",
      houseNumber: "45",
      plz: "60313",
      city: "Frankfurt",
    },
    customer: {
      id: "cust-9",
      name: "Heinz Wolf",
      email: "heinz.wolf@online.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-9",
      name: "Braun Trockenbau",
      email: "info@braun-trockenbau.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Braun Trockenbau",
      verified: true,
    },
    recentMessages: [
      {
        id: "msg-7",
        senderName: "Braun Trockenbau",
        senderRole: "provider",
        content: "Ich werde ca. 2 Tage für die Arbeit benötigen.",
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "BK-2024-010",
    jobTitle: "Heizungswartung",
    description: "Jährliche Wartung der Gasheizung inkl. Reinigung und Funktionsprüfung.",
    category: "Sanitär",
    status: "completed",
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    scheduledDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    scheduledTime: "10:00",
    completedDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    subtotal: 180,
    platformFee: 21.6,
    total: 201.6,
    providerPayout: 158.4,
    paymentStatus: "paid",
    address: {
      street: "Hafenstraße",
      houseNumber: "7",
      plz: "20459",
      city: "Hamburg",
    },
    customer: {
      id: "cust-10",
      name: "Klaus Richter",
      email: "k.richter@mail.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    provider: {
      id: "prov-10",
      name: "Heizung & Sanitär Schmidt",
      email: "service@hs-schmidt.de",
      avatar: "/placeholder.svg?height=40&width=40",
      companyName: "Heizung & Sanitär Schmidt GmbH",
      verified: true,
    },
    recentMessages: [
      {
        id: "msg-8",
        senderName: "Klaus Richter",
        senderRole: "customer",
        content: "Alles bestens, danke!",
        timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
      },
    ],
  },
]

export const adminJobRequestsData: AdminJobRequestDetail[] = [
  {
    id: "JR-2024-001",
    title: "Küche komplett renovieren",
    description:
      "Wir möchten unsere Küche komplett renovieren. Dazu gehören neue Fliesen, Elektrik für zusätzliche Steckdosen, und Malerarbeiten. Die Küche ist ca. 15m² groß.",
    category: "Trockenbau",
    location: "Berlin",
    plz: "10115",
    timeframe: "In den nächsten 2 Wochen",
    budget: 5000,
    budgetMax: 8000,
    photos: ["/placeholder.svg?height=200&width=300"],
    status: "open",
    offerCount: 3,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    customer: {
      id: "cust-1",
      name: "Peter Klein",
      email: "peter.klein@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-002",
    title: "Lampen installieren im Wohnzimmer",
    description:
      "Benötige einen Elektriker für die Installation von 3 Deckenlampen und 2 Wandlampen im Wohnzimmer. Kabel sind bereits vorhanden.",
    category: "Elektriker",
    location: "Hamburg",
    plz: "20095",
    timeframe: "Flexibel",
    budget: 200,
    photos: [],
    status: "in_discussion",
    offerCount: 5,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    customer: {
      id: "cust-2",
      name: "Eva Schulz",
      email: "eva.schulz@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-003",
    title: "DRINGEND: Wasserhahn tropft - Kontakt: 0171-XXXXXXX",
    description:
      "Mein Wasserhahn in der Küche tropft seit gestern. Bitte rufen Sie mich an unter 0171-1234567 oder schreiben Sie mir eine WhatsApp. Meine Adresse ist Musterstraße 123, 80331 München.",
    category: "Sanitär",
    location: "München",
    plz: "80331",
    timeframe: "So schnell wie möglich",
    budget: null,
    photos: [],
    status: "flagged",
    offerCount: 0,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    customer: {
      id: "cust-3",
      name: "Frank Weber",
      email: "frank.weber@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: true,
    flagReason: "personal_data",
    flagNotes: "Enthält Telefonnummer und vollständige Adresse im Titel und Beschreibung.",
    flaggedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    flaggedBy: "Admin Team",
  },
  {
    id: "JR-2024-004",
    title: "Flur und Treppenhaus streichen",
    description:
      "Flur (ca. 8m²) und Treppenhaus (2 Etagen) sollen neu gestrichen werden. Farbe wird vom Handwerker gestellt. Decken müssen nicht gestrichen werden.",
    category: "Maler",
    location: "Köln",
    plz: "50667",
    timeframe: "In den nächsten 4 Wochen",
    budget: 800,
    budgetMax: 1200,
    photos: ["/placeholder.svg?height=200&width=300"],
    status: "filled",
    offerCount: 7,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    customer: {
      id: "cust-4",
      name: "Gabi Meyer",
      email: "gabi.meyer@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-005",
    title: "Rigipswand einziehen für Homeoffice",
    description:
      "Möchte eine Trennwand (ca. 3m breit, 2.5m hoch) im Wohnzimmer einziehen, um ein separates Homeoffice zu schaffen. Mit Tür bitte.",
    category: "Trockenbau",
    location: "Berlin",
    plz: "10243",
    timeframe: "Nächsten Monat",
    budget: 1500,
    photos: ["/placeholder.svg?height=200&width=300"],
    status: "open",
    offerCount: 2,
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000),
    customer: {
      id: "cust-5",
      name: "Heinz Wolf",
      email: "heinz.wolf@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-006",
    title: "💰💰💰 GÜNSTIG GELD VERDIENEN - KEIN HANDWERK 💰💰💰",
    description:
      "Verdienen Sie 5000€ pro Woche von zu Hause! Kein Handwerk nötig. Besuchen Sie unsere Website spam-scam.example.com für mehr Infos. SCHNELL REICH WERDEN!!!",
    category: "Elektriker",
    location: "Frankfurt",
    plz: "60311",
    timeframe: "Sofort",
    budget: null,
    photos: [],
    status: "flagged",
    offerCount: 0,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    customer: {
      id: "cust-6",
      name: "Spam Account",
      email: "spam@example.com",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: true,
    flagReason: "spam",
    flagNotes: "Offensichtlicher Spam. Kein echter Arbeitsauftrag.",
    flaggedAt: new Date(Date.now() - 10 * 60 * 60 * 1000),
    flaggedBy: "Admin Team",
  },
  {
    id: "JR-2024-007",
    title: "Badezimmer komplett sanieren",
    description:
      "Komplette Badsanierung: Alte Fliesen entfernen, neue Fliesen verlegen, Dusche und WC erneuern. Bad ist ca. 6m² groß. Alles inklusive Material bitte.",
    category: "Sanitär",
    location: "Hamburg",
    plz: "22041",
    timeframe: "In 2-3 Monaten",
    budget: 8000,
    budgetMax: 12000,
    photos: ["/placeholder.svg?height=200&width=300", "/placeholder.svg?height=200&width=300"],
    status: "in_discussion",
    offerCount: 4,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000),
    customer: {
      id: "cust-7",
      name: "Maria Schmidt",
      email: "maria.schmidt@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-008",
    title: "Steckdosen im Kinderzimmer nachrüsten",
    description:
      "Im Kinderzimmer fehlen Steckdosen. Benötige 4 zusätzliche Steckdosen an verschiedenen Stellen. Wand ist aus Rigips.",
    category: "Elektriker",
    location: "München",
    plz: "81667",
    timeframe: "Nächste Woche",
    budget: 350,
    photos: [],
    status: "open",
    offerCount: 1,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    customer: {
      id: "cust-8",
      name: "Klaus Richter",
      email: "klaus.richter@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-009",
    title: "Terrassendach montieren",
    description:
      "Fertig gekauftes Terrassendach (4m x 3m) soll montiert werden. Alle Teile sind vorhanden. Benötige nur die Montage.",
    category: "Handwerker",
    location: "Düsseldorf",
    plz: "40210",
    timeframe: "Wunschtermin: 15.02.2025",
    budget: 600,
    photos: ["/placeholder.svg?height=200&width=300"],
    status: "open",
    offerCount: 0,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    customer: {
      id: "cust-9",
      name: "Stefan Braun",
      email: "stefan.braun@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-010",
    title: "Decke abhängen und Spots einbauen",
    description:
      "Wohnzimmerdecke soll abgehängt werden (ca. 25m²) und mit LED-Spots versehen werden. Gerne mit dimmbaren Spots.",
    category: "Trockenbau",
    location: "Berlin",
    plz: "10969",
    timeframe: "Februar/März 2025",
    budget: 2000,
    budgetMax: 3000,
    photos: [],
    status: "closed",
    offerCount: 6,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    customer: {
      id: "cust-10",
      name: "Julia Hoffmann",
      email: "julia.hoffmann@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-011",
    title: "Heizungsrohre isolieren",
    description: "Heizungsrohre im Keller (ca. 30m) sollen nachträglich isoliert werden für bessere Energieeffizienz.",
    category: "Sanitär",
    location: "Köln",
    plz: "50825",
    timeframe: "Flexibel",
    budget: 400,
    photos: ["/placeholder.svg?height=200&width=300"],
    status: "open",
    offerCount: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    customer: {
      id: "cust-11",
      name: "Thomas Müller",
      email: "thomas.mueller@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
  {
    id: "JR-2024-012",
    title: "Fenster streichen (Altbau)",
    description:
      "8 Holzfenster (Altbau, ca. 100 Jahre alt) müssen abgeschliffen und neu gestrichen werden. Innen und außen.",
    category: "Maler",
    location: "Leipzig",
    plz: "04109",
    timeframe: "Frühjahr 2025",
    budget: 1600,
    budgetMax: 2400,
    photos: ["/placeholder.svg?height=200&width=300", "/placeholder.svg?height=200&width=300"],
    status: "in_discussion",
    offerCount: 3,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    customer: {
      id: "cust-12",
      name: "Andrea Fischer",
      email: "andrea.fischer@email.de",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    isFlagged: false,
  },
]
