import type { Conversation, Message } from "@/lib/types"

// Helper to create messages
function createMessage(
  id: string,
  senderId: string,
  senderName: string,
  senderAvatar: string,
  content: string,
  timestamp: Date,
  isCurrentUser: boolean,
): Message {
  return { id, senderId, senderName, senderAvatar, content, timestamp, isCurrentUser }
}

// Mock conversations for customer view
export const customerConversations: Conversation[] = [
  {
    id: "conv-1",
    counterpartyId: "provider-1",
    counterpartyName: "Thomas Müller",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: true,
    context: "booking",
    contextId: "booking-1",
    contextTitle: "Wand streichen",
    lastMessage: "Perfekt, dann sehen wir uns am Montag um 9 Uhr!",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 15), // 15 min ago
    unreadCount: 2,
    messages: [
      createMessage(
        "m1",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Hallo, ich hätte gerne ein Angebot für das Streichen meines Wohnzimmers.",
        new Date(Date.now() - 1000 * 60 * 60 * 24),
        true,
      ),
      createMessage(
        "m2",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Guten Tag! Wie groß ist die Fläche ungefähr?",
        new Date(Date.now() - 1000 * 60 * 60 * 23),
        false,
      ),
      createMessage(
        "m3",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Ca. 35 qm, 3 Wände sollen gestrichen werden.",
        new Date(Date.now() - 1000 * 60 * 60 * 22),
        true,
      ),
      createMessage(
        "m4",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Das kann ich gut machen. Passt Ihnen Montag um 9 Uhr?",
        new Date(Date.now() - 1000 * 60 * 30),
        false,
      ),
      createMessage(
        "m5",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Perfekt, dann sehen wir uns am Montag um 9 Uhr!",
        new Date(Date.now() - 1000 * 60 * 15),
        false,
      ),
    ],
  },
  {
    id: "conv-2",
    counterpartyId: "provider-2",
    counterpartyName: "Klaus Weber",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: true,
    context: "request",
    contextId: "request-1",
    contextTitle: "Armatur tauschen",
    lastMessage: "Ich kann das morgen Vormittag erledigen. Mein Angebot liegt bei 85€.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 45), // 45 min ago
    unreadCount: 1,
    messages: [
      createMessage(
        "m6",
        "provider-2",
        "Klaus Weber",
        "/placeholder.svg?height=40&width=40",
        "Hallo, ich habe Ihren Auftrag gesehen. Ist die Armatur schon gekauft?",
        new Date(Date.now() - 1000 * 60 * 60 * 2),
        false,
      ),
      createMessage(
        "m7",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Ja, die Armatur liegt schon bereit.",
        new Date(Date.now() - 1000 * 60 * 60),
        true,
      ),
      createMessage(
        "m8",
        "provider-2",
        "Klaus Weber",
        "/placeholder.svg?height=40&width=40",
        "Ich kann das morgen Vormittag erledigen. Mein Angebot liegt bei 85€.",
        new Date(Date.now() - 1000 * 60 * 45),
        false,
      ),
    ],
  },
  {
    id: "conv-3",
    counterpartyId: "provider-3",
    counterpartyName: "Anna Schmidt",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "booking",
    contextId: "booking-2",
    contextTitle: "Trockenbau Reparatur",
    lastMessage: "Vielen Dank für die Beauftragung! Ich melde mich kurz vorher nochmal.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 3), // 3 hours ago
    unreadCount: 0,
    messages: [
      createMessage(
        "m9",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Hallo Frau Schmidt, können Sie am Freitag vorbeikommen?",
        new Date(Date.now() - 1000 * 60 * 60 * 5),
        true,
      ),
      createMessage(
        "m10",
        "provider-3",
        "Anna Schmidt",
        "/placeholder.svg?height=40&width=40",
        "Ja, Freitag Nachmittag passt gut. Ich komme gegen 14 Uhr.",
        new Date(Date.now() - 1000 * 60 * 60 * 4),
        false,
      ),
      createMessage(
        "m11",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Super, das passt perfekt!",
        new Date(Date.now() - 1000 * 60 * 60 * 3.5),
        true,
      ),
      createMessage(
        "m12",
        "provider-3",
        "Anna Schmidt",
        "/placeholder.svg?height=40&width=40",
        "Vielen Dank für die Beauftragung! Ich melde mich kurz vorher nochmal.",
        new Date(Date.now() - 1000 * 60 * 60 * 3),
        false,
      ),
    ],
  },
  {
    id: "conv-4",
    counterpartyId: "provider-4",
    counterpartyName: "Michael Hoffmann",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: true,
    context: "request",
    contextId: "request-2",
    contextTitle: "Badezimmer Fliesen",
    lastMessage: "Danke für Ihr Interesse! Leider bin ich diese Woche ausgebucht.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 24), // 1 day ago
    unreadCount: 0,
    messages: [
      createMessage(
        "m13",
        "provider-4",
        "Michael Hoffmann",
        "/placeholder.svg?height=40&width=40",
        "Guten Tag! Ich habe Ihren Auftrag für die Badezimmer Fliesen gesehen.",
        new Date(Date.now() - 1000 * 60 * 60 * 26),
        false,
      ),
      createMessage(
        "m14",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Hallo! Ja, wir brauchen jemanden für ca. 12 qm Wandfliesen.",
        new Date(Date.now() - 1000 * 60 * 60 * 25),
        true,
      ),
      createMessage(
        "m15",
        "provider-4",
        "Michael Hoffmann",
        "/placeholder.svg?height=40&width=40",
        "Danke für Ihr Interesse! Leider bin ich diese Woche ausgebucht.",
        new Date(Date.now() - 1000 * 60 * 60 * 24),
        false,
      ),
    ],
  },
  {
    id: "conv-5",
    counterpartyId: "provider-5",
    counterpartyName: "Stefan Becker",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: true,
    context: "booking",
    contextId: "booking-3",
    contextTitle: "Küchenmontage",
    lastMessage: "Die Montage ist abgeschlossen. Bitte prüfen Sie alles in Ruhe.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 48), // 2 days ago
    unreadCount: 0,
    messages: [
      createMessage(
        "m16",
        "provider-5",
        "Stefan Becker",
        "/placeholder.svg?height=40&width=40",
        "Hallo, ich bin fertig mit der Küchenmontage!",
        new Date(Date.now() - 1000 * 60 * 60 * 49),
        false,
      ),
      createMessage(
        "m17",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Super, vielen Dank! Sieht toll aus.",
        new Date(Date.now() - 1000 * 60 * 60 * 48.5),
        true,
      ),
      createMessage(
        "m18",
        "provider-5",
        "Stefan Becker",
        "/placeholder.svg?height=40&width=40",
        "Die Montage ist abgeschlossen. Bitte prüfen Sie alles in Ruhe.",
        new Date(Date.now() - 1000 * 60 * 60 * 48),
        false,
      ),
    ],
  },
  {
    id: "conv-6",
    counterpartyId: "provider-6",
    counterpartyName: "Lars Schneider",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: true,
    context: "request",
    contextId: "request-3",
    contextTitle: "Fassadenanstrich",
    lastMessage: "Für die Fassade würde ich 2.400€ veranschlagen inkl. Material.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 72), // 3 days ago
    unreadCount: 0,
    messages: [
      createMessage(
        "m19",
        "provider-6",
        "Lars Schneider",
        "/placeholder.svg?height=40&width=40",
        "Guten Tag! Ich mache gerne ein Angebot für den Fassadenanstrich.",
        new Date(Date.now() - 1000 * 60 * 60 * 74),
        false,
      ),
      createMessage(
        "m20",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Wie viel würde das ungefähr kosten?",
        new Date(Date.now() - 1000 * 60 * 60 * 73),
        true,
      ),
      createMessage(
        "m21",
        "provider-6",
        "Lars Schneider",
        "/placeholder.svg?height=40&width=40",
        "Für die Fassade würde ich 2.400€ veranschlagen inkl. Material.",
        new Date(Date.now() - 1000 * 60 * 60 * 72),
        false,
      ),
    ],
  },
  {
    id: "conv-7",
    counterpartyId: "provider-7",
    counterpartyName: "Petra Fischer",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: true,
    context: "booking",
    contextId: "booking-4",
    contextTitle: "Steckdosen Installation",
    lastMessage: "Alles klar, ich bringe das benötigte Material mit.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 96), // 4 days ago
    unreadCount: 0,
    messages: [
      createMessage(
        "m22",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Können Sie auch USB-Steckdosen einbauen?",
        new Date(Date.now() - 1000 * 60 * 60 * 98),
        true,
      ),
      createMessage(
        "m23",
        "provider-7",
        "Petra Fischer",
        "/placeholder.svg?height=40&width=40",
        "Ja natürlich, das mache ich häufig.",
        new Date(Date.now() - 1000 * 60 * 60 * 97),
        false,
      ),
      createMessage(
        "m24",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Perfekt, dann bitte 3x USB-C Steckdosen.",
        new Date(Date.now() - 1000 * 60 * 60 * 96.5),
        true,
      ),
      createMessage(
        "m25",
        "provider-7",
        "Petra Fischer",
        "/placeholder.svg?height=40&width=40",
        "Alles klar, ich bringe das benötigte Material mit.",
        new Date(Date.now() - 1000 * 60 * 60 * 96),
        false,
      ),
    ],
  },
  {
    id: "conv-8",
    counterpartyId: "provider-8",
    counterpartyName: "Markus Wolf",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "request",
    contextId: "request-4",
    contextTitle: "Einbauschrank Maßanfertigung",
    lastMessage: "Für eine Maßanfertigung bräuchte ich erstmal genaue Maße.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 120), // 5 days ago
    unreadCount: 0,
    messages: [
      createMessage(
        "m26",
        "provider-8",
        "Markus Wolf",
        "/placeholder.svg?height=40&width=40",
        "Hallo! Ich baue seit 15 Jahren Einbauschränke nach Maß.",
        new Date(Date.now() - 1000 * 60 * 60 * 122),
        false,
      ),
      createMessage(
        "m27",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Das klingt gut! Was brauchen Sie von mir?",
        new Date(Date.now() - 1000 * 60 * 60 * 121),
        true,
      ),
      createMessage(
        "m28",
        "provider-8",
        "Markus Wolf",
        "/placeholder.svg?height=40&width=40",
        "Für eine Maßanfertigung bräuchte ich erstmal genaue Maße.",
        new Date(Date.now() - 1000 * 60 * 60 * 120),
        false,
      ),
    ],
  },
]

// Mock conversations for provider view (counterparty is customer)
export const providerConversations: Conversation[] = [
  {
    id: "pconv-1",
    counterpartyId: "customer-1",
    counterpartyName: "Max Mustermann",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "booking",
    contextId: "booking-1",
    contextTitle: "Wand streichen",
    lastMessage: "Ja, Montag 9 Uhr passt mir sehr gut!",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 20),
    unreadCount: 1,
    messages: [
      createMessage(
        "pm1",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Guten Tag! Wie groß ist die Fläche ungefähr?",
        new Date(Date.now() - 1000 * 60 * 60 * 23),
        true,
      ),
      createMessage(
        "pm2",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Ca. 35 qm, 3 Wände sollen gestrichen werden.",
        new Date(Date.now() - 1000 * 60 * 60 * 22),
        false,
      ),
      createMessage(
        "pm3",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Das kann ich gut machen. Passt Ihnen Montag um 9 Uhr?",
        new Date(Date.now() - 1000 * 60 * 30),
        true,
      ),
      createMessage(
        "pm4",
        "customer-1",
        "Max Mustermann",
        "/placeholder.svg?height=40&width=40",
        "Ja, Montag 9 Uhr passt mir sehr gut!",
        new Date(Date.now() - 1000 * 60 * 20),
        false,
      ),
    ],
  },
  {
    id: "pconv-2",
    counterpartyId: "customer-2",
    counterpartyName: "Julia Richter",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "request",
    contextId: "request-5",
    contextTitle: "Deckenlampe montieren",
    lastMessage: "Können Sie auch am Wochenende?",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60),
    unreadCount: 1,
    messages: [
      createMessage(
        "pm5",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Ich habe Ihren Auftrag gesehen. Das mache ich gerne!",
        new Date(Date.now() - 1000 * 60 * 60 * 3),
        true,
      ),
      createMessage(
        "pm6",
        "customer-2",
        "Julia Richter",
        "/placeholder.svg?height=40&width=40",
        "Super! Wann hätten Sie Zeit?",
        new Date(Date.now() - 1000 * 60 * 60 * 2),
        false,
      ),
      createMessage(
        "pm7",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Ich könnte Donnerstag Nachmittag.",
        new Date(Date.now() - 1000 * 60 * 60 * 1.5),
        true,
      ),
      createMessage(
        "pm8",
        "customer-2",
        "Julia Richter",
        "/placeholder.svg?height=40&width=40",
        "Können Sie auch am Wochenende?",
        new Date(Date.now() - 1000 * 60 * 60),
        false,
      ),
    ],
  },
  {
    id: "pconv-3",
    counterpartyId: "customer-3",
    counterpartyName: "Peter Neumann",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "booking",
    contextId: "booking-5",
    contextTitle: "Türschloss wechseln",
    lastMessage: "Vielen Dank, hat alles super geklappt!",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    unreadCount: 0,
    messages: [
      createMessage(
        "pm9",
        "customer-3",
        "Peter Neumann",
        "/placeholder.svg?height=40&width=40",
        "Der Schlüssel steckt leider von innen.",
        new Date(Date.now() - 1000 * 60 * 60 * 26),
        false,
      ),
      createMessage(
        "pm10",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Kein Problem, ich bringe Spezialwerkzeug mit.",
        new Date(Date.now() - 1000 * 60 * 60 * 25),
        true,
      ),
      createMessage(
        "pm11",
        "customer-3",
        "Peter Neumann",
        "/placeholder.svg?height=40&width=40",
        "Vielen Dank, hat alles super geklappt!",
        new Date(Date.now() - 1000 * 60 * 60 * 24),
        false,
      ),
    ],
  },
  {
    id: "pconv-4",
    counterpartyId: "customer-4",
    counterpartyName: "Sabine Klein",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "request",
    contextId: "request-6",
    contextTitle: "Bürobeleuchtung erneuern",
    lastMessage: "Können Sie mir einen Kostenvoranschlag schicken?",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    unreadCount: 0,
    messages: [
      createMessage(
        "pm12",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Für LED-Panels im Büro bin ich der richtige Ansprechpartner.",
        new Date(Date.now() - 1000 * 60 * 60 * 50),
        true,
      ),
      createMessage(
        "pm13",
        "customer-4",
        "Sabine Klein",
        "/placeholder.svg?height=40&width=40",
        "Können Sie mir einen Kostenvoranschlag schicken?",
        new Date(Date.now() - 1000 * 60 * 60 * 48),
        false,
      ),
    ],
  },
  {
    id: "pconv-5",
    counterpartyId: "customer-5",
    counterpartyName: "Hans Meier",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "booking",
    contextId: "booking-6",
    contextTitle: "Rollladenreparatur",
    lastMessage: "Perfekt, dann bis Mittwoch!",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 72),
    unreadCount: 0,
    messages: [
      createMessage(
        "pm14",
        "customer-5",
        "Hans Meier",
        "/placeholder.svg?height=40&width=40",
        "Der Rollladen im Schlafzimmer klemmt.",
        new Date(Date.now() - 1000 * 60 * 60 * 74),
        false,
      ),
      createMessage(
        "pm15",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Das ist meistens ein Gurtproblem. Ich komme Mittwoch.",
        new Date(Date.now() - 1000 * 60 * 60 * 73),
        true,
      ),
      createMessage(
        "pm16",
        "customer-5",
        "Hans Meier",
        "/placeholder.svg?height=40&width=40",
        "Perfekt, dann bis Mittwoch!",
        new Date(Date.now() - 1000 * 60 * 60 * 72),
        false,
      ),
    ],
  },
  {
    id: "pconv-6",
    counterpartyId: "customer-6",
    counterpartyName: "Lisa Wagner",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "request",
    contextId: "request-7",
    contextTitle: "Balkongeländer streichen",
    lastMessage: "Welche Farbe empfehlen Sie für Metall?",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 96),
    unreadCount: 0,
    messages: [
      createMessage(
        "pm17",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Für Balkongeländer nutze ich gerne Hammerite.",
        new Date(Date.now() - 1000 * 60 * 60 * 98),
        true,
      ),
      createMessage(
        "pm18",
        "customer-6",
        "Lisa Wagner",
        "/placeholder.svg?height=40&width=40",
        "Welche Farbe empfehlen Sie für Metall?",
        new Date(Date.now() - 1000 * 60 * 60 * 96),
        false,
      ),
    ],
  },
  {
    id: "pconv-7",
    counterpartyId: "customer-7",
    counterpartyName: "Frank Braun",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "booking",
    contextId: "booking-7",
    contextTitle: "Fensterabdichtung",
    lastMessage: "Die Rechnung habe ich erhalten, wird überwiesen.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 120),
    unreadCount: 0,
    messages: [
      createMessage(
        "pm19",
        "provider-1",
        "Thomas Müller",
        "/placeholder.svg?height=40&width=40",
        "Die Arbeit ist abgeschlossen, hier ist die Rechnung.",
        new Date(Date.now() - 1000 * 60 * 60 * 122),
        true,
      ),
      createMessage(
        "pm20",
        "customer-7",
        "Frank Braun",
        "/placeholder.svg?height=40&width=40",
        "Die Rechnung habe ich erhalten, wird überwiesen.",
        new Date(Date.now() - 1000 * 60 * 60 * 120),
        false,
      ),
    ],
  },
  {
    id: "pconv-8",
    counterpartyId: "customer-8",
    counterpartyName: "Maria Schuster",
    counterpartyAvatar: "/placeholder.svg?height=40&width=40",
    counterpartyVerified: false,
    context: "request",
    contextId: "request-8",
    contextTitle: "Regale montieren",
    lastMessage: "Ich möchte 5 IKEA Kallax Regale aufbauen lassen.",
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 144),
    unreadCount: 0,
    messages: [
      createMessage(
        "pm21",
        "customer-8",
        "Maria Schuster",
        "/placeholder.svg?height=40&width=40",
        "Ich möchte 5 IKEA Kallax Regale aufbauen lassen.",
        new Date(Date.now() - 1000 * 60 * 60 * 144),
        false,
      ),
    ],
  },
]

// Helper function to format relative time in German
export function formatRelativeTime(date: Date): string {
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffMins = Math.floor(diffMs / (1000 * 60))
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60))
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))

  if (diffMins < 1) return "Gerade eben"
  if (diffMins < 60) return `vor ${diffMins} Min.`
  if (diffHours < 24) return `vor ${diffHours} Std.`
  if (diffDays === 1) return "Gestern"
  if (diffDays < 7) return `vor ${diffDays} Tagen`
  return date.toLocaleDateString("de-DE", { day: "2-digit", month: "2-digit" })
}
