import type {
  ServiceListing,
  JobRequest,
  Booking,
  Message,
  Offer,
  ListingDetail,
  Review,
  JobRequestDetail,
  ActivityEvent,
  Order,
  BookingDetail,
  ProviderStats,
  ProviderBookingRequest,
  JobBoardListing,
  OnboardingTask,
  ProviderListing,
  ProviderListingDetail,
  ProviderJob,
  ProviderJobDetail, // Add ProviderJobDetail import
  JobBoardItem, // Add JobBoardItem import
  ProviderWorkRequestDetail, // Add ProviderWorkRequestDetail import
  EarningsSummary,
  Transaction,
} from "@/lib/types"

export const mockListings: ServiceListing[] = [
  {
    id: "1",
    providerId: "provider-1",
    providerName: "Klaus Müller",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Badezimmerrenovierung - Komplettservice",
    description: "Professionelle Renovierung Ihres Badezimmers inkl. Fliesen, Sanitär und Elektrik",
    category: "Sanitär",
    priceFrom: 2500,
    priceUnit: "Projekt",
    rating: 4.8,
    reviewCount: 127,
    verified: true,
    responseTime: "< 2 Std.",
    completedJobs: 89,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "2",
    providerId: "provider-2",
    providerName: "Thomas Weber",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Elektriker - Schneller Service",
    description: "Elektroinstallationen, Reparaturen und Fehlersuche",
    category: "Elektrik",
    priceFrom: 65,
    priceUnit: "Stunde",
    rating: 4.9,
    reviewCount: 203,
    verified: true,
    responseTime: "< 1 Std.",
    completedJobs: 156,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "3",
    providerId: "provider-3",
    providerName: "Maria Schmidt",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Malerarbeiten & Lackierung",
    description: "Innen- und Außenanstriche, Tapezierarbeiten und Fassadengestaltung",
    category: "Maler",
    priceFrom: 45,
    priceUnit: "Stunde",
    rating: 4.7,
    reviewCount: 94,
    verified: true,
    responseTime: "< 3 Std.",
    completedJobs: 67,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
]

export const mockJobRequests: JobRequest[] = [
  {
    id: "job-1",
    customerId: "customer-1",
    customerName: "Anna Bauer",
    title: "Küche renovieren - Fliesen und Arbeitsplatte",
    description:
      "Suche Handwerker für Fliesenarbeiten in der Küche und Installation einer neuen Arbeitsplatte. Ca. 15 qm Fläche.",
    category: "Fliesen",
    budget: 3500,
    location: "Berlin Mitte",
    urgency: "normal",
    createdAt: new Date("2024-01-15"),
    offerCount: 8,
    status: "open",
  },
  {
    id: "job-2",
    customerId: "customer-2",
    customerName: "Peter Wagner",
    title: "Dringende Heizungsreparatur",
    description: "Heizung funktioniert nicht mehr. Brauche dringend Hilfe, da es es sehr kalt ist.",
    category: "Heizung",
    budget: 500,
    location: "München",
    urgency: "urgent",
    createdAt: new Date("2024-01-18"),
    offerCount: 12,
    status: "open",
  },
  {
    id: "job-3",
    customerId: "customer-3",
    customerName: "Julia Schneider",
    title: "Terrassenbau im Garten",
    description: "Möchte eine Holzterrasse im Garten bauen lassen. Fläche ca. 20 qm.",
    category: "Garten & Außen",
    budget: 5000,
    location: "Hamburg",
    urgency: "flexible",
    createdAt: new Date("2024-01-10"),
    offerCount: 5,
    status: "open",
  },
]

export const mockBookings: Booking[] = [
  {
    id: "booking-1",
    jobTitle: "Badezimmerrenovierung",
    providerId: "provider-1",
    providerName: "Klaus Müller",
    customerId: "customer-1",
    customerName: "Anna Bauer",
    status: "in_progress",
    scheduledDate: new Date("2024-02-01"),
    totalAmount: 2800,
    category: "Sanitär",
  },
  {
    id: "booking-2",
    jobTitle: "Elektriker - Schneller Service",
    providerId: "provider-2",
    providerName: "Thomas Weber",
    customerId: "customer-2",
    customerName: "Peter Wagner",
    status: "confirmed",
    scheduledDate: new Date("2024-01-25"),
    totalAmount: 320,
    category: "Elektrik",
  },
  {
    id: "booking-3",
    jobTitle: "Malerarbeiten Wohnzimmer",
    providerId: "provider-3",
    providerName: "Maria Schmidt",
    customerId: "customer-3",
    customerName: "Julia Schneider",
    status: "completed",
    scheduledDate: new Date("2024-01-10"),
    totalAmount: 450,
    category: "Maler",
  },
]

export const mockMessages: Message[] = [
  {
    id: "msg-1",
    senderId: "provider-1",
    senderName: "Klaus Müller",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Hallo! Ich habe Ihre Anfrage gesehen. Wann kann ich vorbeikommen, um mir das Bad anzuschauen?",
    timestamp: new Date("2024-01-15T10:30:00"),
    isCurrentUser: false,
  },
  {
    id: "msg-2",
    senderId: "customer-1",
    senderName: "Anna Bauer",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Hallo Klaus! Wie wäre es mit Donnerstag um 14 Uhr? Passt Ihnen das?",
    timestamp: new Date("2024-01-15T11:15:00"),
    isCurrentUser: true,
  },
  {
    id: "msg-3",
    senderId: "provider-1",
    senderName: "Klaus Müller",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Perfekt! Donnerstag 14 Uhr passt mir sehr gut. Bis dann!",
    timestamp: new Date("2024-01-15T11:20:00"),
    isCurrentUser: false,
  },
  {
    id: "msg-4",
    senderId: "customer-1",
    senderName: "Anna Bauer",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Super, bis Donnerstag!",
    timestamp: new Date("2024-01-15T11:22:00"),
    isCurrentUser: true,
  },
]

export const mockOffers: Offer[] = [
  {
    id: "offer-1",
    jobRequestId: "job-1",
    providerId: "provider-1",
    providerName: "Klaus Müller",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    providerRating: 4.8,
    providerReviewCount: 127,
    verified: true,
    price: 3200,
    estimatedDuration: "4-5 Tage",
    message:
      "Guten Tag! Ich habe über 15 Jahre Erfahrung mit Fliesenarbeiten und würde mich freuen, Ihre Küche zu renovieren. Der Preis beinhaltet Material und Arbeit.",
    createdAt: new Date("2024-01-16T09:00:00"),
  },
  {
    id: "offer-2",
    jobRequestId: "job-1",
    providerId: "provider-4",
    providerName: "Stefan Fischer",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    providerRating: 4.6,
    providerReviewCount: 82,
    verified: true,
    price: 2950,
    estimatedDuration: "5-6 Tage",
    message:
      "Hallo! Ich kann Ihnen ein gutes Angebot für die Fliesenarbeiten machen. Ich arbeite sehr sorgfältig und präzise.",
    createdAt: new Date("2024-01-16T10:30:00"),
  },
  {
    id: "offer-3",
    jobRequestId: "job-1",
    providerId: "provider-5",
    providerName: "Michael Braun",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    providerRating: 4.9,
    providerReviewCount: 156,
    verified: true,
    price: 3450,
    estimatedDuration: "3-4 Tage",
    message:
      "Ihre Küchenrenovierung kann ich schnell und professionell durchführen. Hochwertige Materialien inklusive.",
    createdAt: new Date("2024-01-16T14:15:00"),
  },
]

export const mockSearchListings: ServiceListing[] = [
  ...mockListings,
  {
    id: "4",
    providerId: "provider-4",
    providerName: "Stefan Fischer",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Trockenbau & Rigips Arbeiten",
    description: "Professioneller Trockenbau, Ständerwerk, Deckenverkleidungen und Dachausbau",
    category: "Trockenbau",
    priceFrom: 55,
    priceUnit: "Stunde",
    rating: 4.6,
    reviewCount: 82,
    verified: true,
    responseTime: "< 2 Std.",
    completedJobs: 64,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "5",
    providerId: "provider-5",
    providerName: "Michael Braun",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Sanitärinstallation & Notdienst",
    description: "Heizung, Sanitär, Rohrreinigung und 24h Notdienst",
    category: "Sanitär",
    priceFrom: 75,
    priceUnit: "Stunde",
    rating: 4.9,
    reviewCount: 156,
    verified: true,
    responseTime: "< 30 Min.",
    completedJobs: 234,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "6",
    providerId: "provider-6",
    providerName: "Andrea Hoffmann",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Innenausbau & Renovierung",
    description: "Komplette Wohnungsrenovierung, Böden, Türen und Fenster",
    category: "Handwerker",
    priceFrom: 50,
    priceUnit: "Stunde",
    rating: 4.7,
    reviewCount: 118,
    verified: false,
    responseTime: "< 4 Std.",
    completedJobs: 91,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "7",
    providerId: "provider-7",
    providerName: "Jens Richter",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Maler & Tapezierarbeiten",
    description: "Hochwertige Malerarbeiten, kreative Wandgestaltung und Fassadenanstrich",
    category: "Maler",
    priceFrom: 40,
    priceUnit: "Stunde",
    rating: 4.5,
    reviewCount: 67,
    verified: true,
    responseTime: "< 3 Std.",
    completedJobs: 52,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "8",
    providerId: "provider-8",
    providerName: "Markus Zimmermann",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Elektroinstallationen Komplett",
    description: "Neuinstallation, Altbausanierung, Smart Home und Sicherheitstechnik",
    category: "Elektrik",
    priceFrom: 70,
    priceUnit: "Stunde",
    rating: 4.8,
    reviewCount: 143,
    verified: true,
    responseTime: "< 2 Std.",
    completedJobs: 112,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "9",
    providerId: "provider-9",
    providerName: "Sabine Keller",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Fliesenarbeiten & Naturstein",
    description: "Fliesen, Mosaik, Naturstein und Terrassenplatten",
    category: "Fliesen",
    priceFrom: 55,
    priceUnit: "qm",
    rating: 4.9,
    reviewCount: 89,
    verified: true,
    responseTime: "< 2 Std.",
    completedJobs: 78,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "10",
    providerId: "provider-10",
    providerName: "Dirk Schulze",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Trockenbau Spezialist",
    description: "Trennwände, abgehängte Decken, Schallschutz und Brandschutz",
    category: "Trockenbau",
    priceFrom: 48,
    priceUnit: "Stunde",
    rating: 4.4,
    reviewCount: 56,
    verified: false,
    responseTime: "< 5 Std.",
    completedJobs: 43,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "11",
    providerId: "provider-11",
    providerName: "Uwe Hartmann",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Heizung & Klimaanlagen",
    description: "Heizungsinstallation, Wartung, Klimaanlagen und Wärmepumpen",
    category: "Sanitär",
    priceFrom: 85,
    priceUnit: "Stunde",
    rating: 4.7,
    reviewCount: 102,
    verified: true,
    responseTime: "< 3 Std.",
    completedJobs: 87,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "12",
    providerId: "provider-12",
    providerName: "Frank Neumann",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    title: "Allround Handwerker Service",
    description: "Montagearbeiten, Reparaturen, Möbelaufbau und Hausmeisterservice",
    category: "Handwerker",
    priceFrom: 35,
    priceUnit: "Stunde",
    rating: 4.6,
    reviewCount: 211,
    verified: true,
    responseTime: "< 1 Std.",
    completedJobs: 189,
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
]

export const mockReviews: Review[] = [
  {
    id: "review-1",
    customerId: "customer-1",
    customerName: "Anna Bauer",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    comment:
      "Herr Müller hat unser Badezimmer komplett renoviert. Sehr professionelle Arbeit, pünktlich und sauber. Absolute Empfehlung!",
    createdAt: new Date("2024-01-10"),
    jobCategory: "Badezimmerrenovierung",
  },
  {
    id: "review-2",
    customerId: "customer-2",
    customerName: "Peter Wagner",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    comment: "Schnelle Terminvergabe, faire Preise und exzellente Qualität. Die Fliesen sehen perfekt aus!",
    createdAt: new Date("2024-01-05"),
    jobCategory: "Fliesenarbeiten",
  },
  {
    id: "review-3",
    customerId: "customer-3",
    customerName: "Julia Schneider",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4,
    comment:
      "Gute Arbeit, freundlicher Kontakt. Kleiner Punktabzug weil der Termin um einen Tag verschoben werden musste.",
    createdAt: new Date("2023-12-20"),
    jobCategory: "Sanitärinstallation",
  },
  {
    id: "review-4",
    customerId: "customer-4",
    customerName: "Markus Hoffmann",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    comment: "Zum zweiten Mal beauftragt - wieder top Ergebnis! Sehr zuverlässig und kompetent.",
    createdAt: new Date("2023-12-15"),
    jobCategory: "Badezimmerrenovierung",
  },
  {
    id: "review-5",
    customerId: "customer-5",
    customerName: "Sandra Klein",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    comment: "Unser altes Bad ist jetzt wie neu. Alles wurde genau nach Plan umgesetzt. Vielen Dank!",
    createdAt: new Date("2023-12-01"),
    jobCategory: "Komplettumbau",
  },
]

export const mockListingDetail: ListingDetail = {
  id: "1",
  providerId: "provider-1",
  providerName: "Klaus Müller",
  providerAvatar: "/placeholder.svg?height=80&width=80",
  title: "Badezimmerrenovierung - Komplettservice",
  description: "Professionelle Renovierung Ihres Badezimmers inkl. Fliesen, Sanitär und Elektrik",
  fullDescription:
    "Mit über 15 Jahren Erfahrung biete ich Ihnen einen kompletten Renovierungsservice für Ihr Badezimmer. Von der Planung bis zur Fertigstellung bekommen Sie alles aus einer Hand. Ich arbeite ausschließlich mit hochwertigen Materialien deutscher Markenhersteller und lege großen Wert auf saubere, präzise Arbeit. Gerne berate ich Sie auch bei der Auswahl von Fliesen, Armaturen und Sanitärobjekten.",
  category: "Sanitär",
  priceFrom: 2500,
  priceUnit: "Projekt",
  rating: 4.8,
  reviewCount: 127,
  verified: true,
  responseTime: "< 2 Std.",
  completedJobs: 89,
  imageUrl: "/placeholder.svg?height=400&width=600",
  photos: [
    "/placeholder.svg?height=500&width=700",
    "/placeholder.svg?height=500&width=700",
    "/placeholder.svg?height=500&width=700",
    "/placeholder.svg?height=500&width=700",
    "/placeholder.svg?height=500&width=700",
  ],
  services: [
    "Komplette Badezimmerrenovierung",
    "Fliesen- und Natursteinarbeiten",
    "Sanitärinstallation (Dusche, WC, Waschbecken)",
    "Elektroinstallation im Nassbereich",
    "Trockenbau und Vorwandinstallation",
    "Abdichtung nach DIN 18534",
    "Fußbodenheizung",
    "Beratung und Planung inklusive",
  ],
  serviceArea: {
    city: "Berlin",
    radius: 25,
  },
  reviews: mockReviews,
}

export const mockListingDetailUnverified: ListingDetail = {
  ...mockListingDetail,
  id: "unverified-1",
  providerId: "provider-unverified",
  providerName: "Max Neumann",
  providerAvatar: "/placeholder.svg?height=80&width=80",
  verified: false,
  rating: 4.2,
  reviewCount: 12,
  completedJobs: 8,
  reviews: [],
}

export const mockCustomerJobRequests: JobRequest[] = [
  {
    id: "my-job-1",
    customerId: "current-user",
    customerName: "Max Mustermann",
    title: "Küche renovieren - Fliesen und Arbeitsplatte",
    description:
      "Suche Handwerker für Fliesenarbeiten in der Küche und Installation einer neuen Arbeitsplatte. Ca. 15 qm Fläche.",
    category: "Fliesen",
    budget: 3500,
    location: "Berlin Mitte",
    plz: "10115",
    urgency: "normal",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    offerCount: 8,
    status: "open",
  },
  {
    id: "my-job-2",
    customerId: "current-user",
    customerName: "Max Mustermann",
    title: "Badezimmer komplett sanieren",
    description: "Altes Badezimmer soll komplett erneuert werden inkl. Fliesen, Sanitär und Elektrik.",
    category: "Sanitär",
    budget: 8500,
    location: "Berlin Prenzlauer Berg",
    plz: "10405",
    urgency: "normal",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    offerCount: 12,
    status: "in_discussion",
  },
  {
    id: "my-job-3",
    customerId: "current-user",
    customerName: "Max Mustermann",
    title: "Elektrik im Altbau modernisieren",
    description: "Komplette Elektroinstallation in einer 80qm Altbauwohnung erneuern.",
    category: "Elektrik",
    budget: 6000,
    location: "Berlin Kreuzberg",
    plz: "10965",
    urgency: "flexible",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    offerCount: 6,
    status: "in_discussion",
  },
  {
    id: "my-job-4",
    customerId: "current-user",
    customerName: "Max Mustermann",
    title: "Wände streichen im Wohnzimmer",
    description: "Ca. 35qm Wohnzimmer soll neu gestrichen werden, weiße Farbe.",
    category: "Maler",
    budget: 800,
    location: "Berlin Charlottenburg",
    plz: "10627",
    urgency: "flexible",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    offerCount: 15,
    status: "filled",
  },
  {
    id: "my-job-5",
    customerId: "current-user",
    customerName: "Max Mustermann",
    title: "Trockenbau Kinderzimmer",
    description: "Raumteiler im Kinderzimmer mit Rigips erstellen.",
    category: "Trockenbau",
    budget: 1200,
    location: "Berlin Friedrichshain",
    plz: "10243",
    urgency: "normal",
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000),
    offerCount: 4,
    status: "filled",
  },
  {
    id: "my-job-6",
    customerId: "current-user",
    customerName: "Max Mustermann",
    title: "Wasserhahn austauschen",
    description: "Küchenwasserhahn tropft und muss ersetzt werden.",
    category: "Sanitär",
    budget: 150,
    location: "Berlin Mitte",
    plz: "10117",
    urgency: "urgent",
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    offerCount: 9,
    status: "closed",
  },
  {
    id: "my-job-7",
    customerId: "current-user",
    customerName: "Max Mustermann",
    title: "Parkett verlegen",
    description: "Neues Eichenparkett im Schlafzimmer verlegen, ca. 18qm.",
    category: "Handwerker",
    budget: 2200,
    location: "Berlin Schöneberg",
    plz: "10823",
    urgency: "normal",
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    offerCount: 7,
    status: "closed",
  },
]

export const mockJobRequestDetail: JobRequestDetail = {
  id: "my-job-1",
  customerId: "current-user",
  customerName: "Max Mustermann",
  title: "Küche renovieren - Fliesen und Arbeitsplatte",
  description:
    "Suche Handwerker für Fliesenarbeiten in der Küche und Installation einer neuen Arbeitsplatte. Die alten Fliesen müssen entfernt und entsorgt werden. Die Arbeitsplatte soll aus Granit sein, Farbe: anthrazit. Bitte nur Angebote mit Materialkosten.",
  category: "Fliesen",
  budget: 3500,
  location: "Berlin Mitte",
  plz: "10115",
  urgency: "normal",
  createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  offerCount: 5,
  status: "open",
  photos: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
  timeframe: "In den nächsten 2-4 Wochen",
  accessNotes: "Schlüssel kann beim Nachbarn (Hr. Schmidt, 2. OG links) abgeholt werden.",
}

export const mockJobRequestDetailClosed: JobRequestDetail = {
  ...mockJobRequestDetail,
  id: "my-job-closed",
  status: "closed",
  offerCount: 12,
}

export const mockJobRequestDetailNoOffers: JobRequestDetail = {
  ...mockJobRequestDetail,
  id: "my-job-no-offers",
  offerCount: 0,
}

export const mockActivityTimeline: ActivityEvent[] = [
  {
    id: "activity-1",
    type: "published",
    title: "Auftrag veröffentlicht",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "activity-2",
    type: "offer_received",
    title: "1. Antwort erhalten",
    description: "Klaus Müller hat ein Angebot gesendet",
    timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "activity-3",
    type: "offer_received",
    title: "2. Antwort erhalten",
    description: "Stefan Fischer hat ein Angebot gesendet",
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "activity-4",
    type: "message",
    title: "Neue Nachricht",
    description: "Klaus Müller hat geantwortet",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
  },
  {
    id: "activity-5",
    type: "offer_received",
    title: "3. Antwort erhalten",
    description: "Michael Braun hat ein Angebot gesendet",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
]

export const mockDetailOffers: Offer[] = [
  {
    id: "detail-offer-1",
    jobRequestId: "my-job-1",
    providerId: "provider-1",
    providerName: "Klaus Müller",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    providerRating: 4.8,
    providerReviewCount: 127,
    verified: true,
    price: 3200,
    estimatedDuration: "4-5 Tage",
    message:
      "Guten Tag! Ich habe über 15 Jahre Erfahrung mit Fliesenarbeiten und würde mich freuen, Ihre Küche zu renovieren. Der Preis beinhaltet Material und Arbeit.",
    createdAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "detail-offer-2",
    jobRequestId: "my-job-1",
    providerId: "provider-4",
    providerName: "Stefan Fischer",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    providerRating: 4.6,
    providerReviewCount: 82,
    verified: true,
    price: 2950,
    estimatedDuration: "5-6 Tage",
    message:
      "Hallo! Ich kann Ihnen ein gutes Angebot für die Fliesenarbeiten machen. Ich arbeite sehr sorgfältig und präzise. Granit-Arbeitsplatten sind meine Spezialität.",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "detail-offer-3",
    jobRequestId: "my-job-1",
    providerId: "provider-5",
    providerName: "Michael Braun",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    providerRating: 4.9,
    providerReviewCount: 156,
    verified: true,
    price: 3450,
    estimatedDuration: "3-4 Tage",
    message:
      "Ihre Küchenrenovierung kann ich schnell und professionell durchführen. Hochwertige Materialien inklusive. Ich kann bereits nächste Woche anfangen.",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: "detail-offer-4",
    jobRequestId: "my-job-1",
    providerId: "provider-9",
    providerName: "Sabine Keller",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    providerRating: 4.9,
    providerReviewCount: 89,
    verified: true,
    price: 3100,
    estimatedDuration: "4 Tage",
    message:
      "Sehr geehrter Herr Mustermann, gerne übernehme ich die Fliesenarbeiten und Installation der Granitplatte. Referenzbilder auf Anfrage.",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: "detail-offer-5",
    jobRequestId: "my-job-1",
    providerId: "provider-6",
    providerName: "Andrea Hoffmann",
    providerAvatar: "/placeholder.svg?height=48&width=48",
    providerRating: 4.7,
    providerReviewCount: 118,
    verified: false,
    price: 2800,
    estimatedDuration: "5-7 Tage",
    message: "Hallo! Ich biete Ihnen einen fairen Preis für die Renovierung. Besichtigung vor Ort möglich.",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
]

export const mockProviderJobDetails: Record<string, ProviderJobDetail> = {
  "job-detail-1": {
    id: "job-detail-1",
    jobTitle: "Badezimmerrenovierung komplett",
    customerId: "customer-1",
    customerName: "Anna Bauer",
    customerAvatar: "/placeholder.svg?height=64&width=64",
    category: "Sanitär",
    status: "requested",
    requestedDate: new Date("2024-02-15"),
    requestedTime: "10:00",
    amount: 2800,
    city: "Berlin",
    createdAt: new Date("2024-01-20"),
    description:
      "Komplette Renovierung des Badezimmers inkl. neuer Fliesen, Austausch der Sanitäranlagen und Installation einer neuen Duschkabine. Das Bad ist ca. 8 qm groß.",
    photos: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    accessNotes: "Schlüssel liegt beim Nachbarn (Wohnung 3B). Bitte vorher anrufen.",
    address: {
      street: "Unter den Linden",
      houseNumber: "42",
      plz: "10117",
      city: "Berlin",
    },
    customerRating: 4.9,
    customerJobsCompleted: 5,
  },
  "job-detail-2": {
    id: "job-detail-2",
    jobTitle: "Elektroinstallation Küche",
    customerId: "customer-2",
    customerName: "Peter Wagner",
    customerAvatar: "/placeholder.svg?height=64&width=64",
    category: "Elektrik",
    status: "payment_pending",
    requestedDate: new Date("2024-02-10"),
    requestedTime: "14:00",
    amount: 650,
    city: "Berlin",
    createdAt: new Date("2024-01-18"),
    description: "Neue Steckdosen und Anschlüsse für Küchengeräte installieren. Insgesamt 6 neue Steckdosen benötigt.",
    photos: ["/placeholder.svg?height=400&width=600"],
    address: {
      street: "Friedrichstraße",
      houseNumber: "123",
      plz: "10117",
      city: "Berlin",
    },
    customerRating: 4.7,
    customerJobsCompleted: 3,
  },
  "job-detail-3": {
    id: "job-detail-3",
    jobTitle: "Wohnzimmer streichen",
    customerId: "customer-3",
    customerName: "Julia Schneider",
    customerAvatar: "/placeholder.svg?height=64&width=64",
    category: "Maler",
    status: "scheduled",
    requestedDate: new Date("2024-02-20"),
    requestedTime: "09:00",
    amount: 480,
    city: "Berlin",
    createdAt: new Date("2024-01-15"),
    description:
      "Wohnzimmer komplett neu streichen. Wände in hellem Grau, Decke weiß. Fläche ca. 35 qm. Farbe kann mitgebracht werden.",
    photos: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    address: {
      street: "Prenzlauer Allee",
      houseNumber: "88",
      plz: "10405",
      city: "Berlin",
    },
    customerRating: 5.0,
    customerJobsCompleted: 8,
  },
  "job-detail-4": {
    id: "job-detail-4",
    jobTitle: "Heizungsreparatur",
    customerId: "customer-4",
    customerName: "Michael Braun",
    customerAvatar: "/placeholder.svg?height=64&width=64",
    category: "Heizung",
    status: "in_progress",
    requestedDate: new Date("2024-01-25"),
    requestedTime: "11:00",
    amount: 320,
    city: "Berlin",
    createdAt: new Date("2024-01-22"),
    description: "Heizung im Wohnzimmer wird nicht warm. Vermutlich muss entlüftet oder ein Ventil getauscht werden.",
    photos: ["/placeholder.svg?height=400&width=600"],
    address: {
      street: "Kastanienallee",
      houseNumber: "15",
      plz: "10435",
      city: "Berlin",
    },
    customerRating: 4.5,
    customerJobsCompleted: 2,
  },
  "job-detail-5": {
    id: "job-detail-5",
    jobTitle: "Fliesenarbeiten Bad",
    customerId: "customer-5",
    customerName: "Sarah Hoffmann",
    customerAvatar: "/placeholder.svg?height=64&width=64",
    category: "Fliesen",
    status: "completed",
    requestedDate: new Date("2024-01-10"),
    requestedTime: "08:00",
    amount: 1200,
    city: "Berlin",
    createdAt: new Date("2024-01-02"),
    description: "Neue Bodenfliesen im Badezimmer verlegt. Alles zur vollsten Zufriedenheit erledigt.",
    photos: ["/placeholder.svg?height=400&width=600"],
    address: {
      street: "Schönhauser Allee",
      houseNumber: "67",
      plz: "10437",
      city: "Berlin",
    },
    customerRating: 4.8,
    customerJobsCompleted: 12,
  },
}

export const mockOrders: Order[] = [
  {
    id: "order-1",
    jobTitle: "Badezimmerrenovierung - Komplettservice",
    providerId: "provider-1",
    providerName: "Klaus Müller",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    customerId: "customer-1",
    status: "scheduled",
    scheduledDate: new Date("2024-02-15"),
    scheduledTime: "09:00",
    totalAmount: 2800,
    category: "Sanitär",
  },
  {
    id: "order-2",
    jobTitle: "Elektrische Leitungen prüfen",
    providerId: "provider-2",
    providerName: "Thomas Weber",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    customerId: "customer-1",
    status: "payment_pending",
    scheduledDate: new Date("2024-02-18"),
    scheduledTime: "14:00",
    totalAmount: 195,
    category: "Elektrik",
  },
  {
    id: "order-3",
    jobTitle: "Wohnzimmer streichen",
    providerId: "provider-3",
    providerName: "Maria Schmidt",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    customerId: "customer-1",
    status: "in_progress",
    scheduledDate: new Date("2024-02-10"),
    scheduledTime: "08:00",
    totalAmount: 650,
    category: "Maler",
  },
  {
    id: "order-4",
    jobTitle: "Küchenfliesen verlegen",
    providerId: "provider-4",
    providerName: "Hans Becker",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    customerId: "customer-1",
    status: "completed",
    scheduledDate: new Date("2024-01-25"),
    scheduledTime: "10:00",
    totalAmount: 1200,
    category: "Fliesen",
  },
  {
    id: "order-5",
    jobTitle: "Trockenbau Dachgeschoss",
    providerId: "provider-5",
    providerName: "Stefan Klein",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    customerId: "customer-1",
    status: "requested",
    scheduledDate: new Date("2024-02-20"),
    scheduledTime: "07:30",
    totalAmount: 3500,
    category: "Trockenbau",
  },
  {
    id: "order-6",
    jobTitle: "Heizung warten",
    providerId: "provider-6",
    providerName: "Michael Braun",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    customerId: "customer-1",
    status: "completed",
    scheduledDate: new Date("2024-01-20"),
    scheduledTime: "11:00",
    totalAmount: 180,
    category: "Heizung",
  },
  {
    id: "order-7",
    jobTitle: "Fenster abdichten",
    providerId: "provider-7",
    providerName: "Andreas Hoffmann",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    customerId: "customer-1",
    status: "scheduled",
    scheduledDate: new Date("2024-02-22"),
    scheduledTime: "13:00",
    totalAmount: 320,
    category: "Fenster",
  },
  {
    id: "order-8",
    jobTitle: "Garten umgestalten",
    providerId: "provider-8",
    providerName: "Lisa Neumann",
    providerAvatar: "/placeholder.svg?height=40&width=40",
    customerId: "customer-1",
    status: "payment_pending",
    scheduledDate: new Date("2024-03-01"),
    scheduledTime: "08:00",
    totalAmount: 2100,
    category: "Garten",
  },
]

export const mockBookingDetails: Record<string, BookingDetail> = {
  "booking-1": {
    id: "booking-1",
    jobTitle: "Badezimmerrenovierung - Komplettservice",
    description:
      "Vollständige Renovierung des Badezimmers inklusive Fliesen, Sanitäranlagen und Elektrik. Duschkabine und Waschbecken werden ersetzt.",
    providerId: "provider-1",
    providerName: "Klaus Müller",
    providerAvatar: "/placeholder.svg?height=64&width=64",
    providerRating: 4.8,
    providerReviewCount: 127,
    verified: true,
    customerId: "customer-1",
    customerName: "Max Mustermann",
    status: "in_progress",
    scheduledDate: new Date("2024-02-01"),
    scheduledTime: "09:00",
    totalAmount: 2800,
    serviceFee: 336,
    category: "Sanitär",
    address: {
      street: "Musterstraße",
      houseNumber: "42",
      plz: "10115",
      city: "Berlin",
    },
    accessNotes: "Schlüssel beim Nachbarn (Hr. Schmidt, 2. OG links) abholen.",
    photos: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    hasReview: false,
  },
  "booking-needs-payment": {
    id: "booking-needs-payment",
    jobTitle: "Elektriker - Steckdoseninstallation",
    description: "Installation von 5 neuen Steckdosen im Wohnzimmer und Arbeitszimmer.",
    providerId: "provider-2",
    providerName: "Thomas Weber",
    providerAvatar: "/placeholder.svg?height=64&width=64",
    providerRating: 4.9,
    providerReviewCount: 203,
    verified: true,
    customerId: "customer-1",
    customerName: "Max Mustermann",
    status: "needs_payment",
    scheduledDate: new Date("2024-02-15"),
    scheduledTime: "14:00",
    totalAmount: 320,
    serviceFee: 38.4,
    category: "Elektrik",
    address: {
      street: "Hauptstraße",
      houseNumber: "15a",
      plz: "10178",
      city: "Berlin",
    },
    photos: [],
    hasReview: false,
  },
  "booking-completed": {
    id: "booking-completed",
    jobTitle: "Malerarbeiten Wohnzimmer",
    description:
      "Komplettes Streichen des Wohnzimmers inklusive Decke. Farbe: RAL 9010 Reinweiß. Möbel wurden abgedeckt.",
    providerId: "provider-3",
    providerName: "Maria Schmidt",
    providerAvatar: "/placeholder.svg?height=64&width=64",
    providerRating: 4.7,
    providerReviewCount: 94,
    verified: true,
    customerId: "customer-1",
    customerName: "Max Mustermann",
    status: "completed",
    scheduledDate: new Date("2024-01-10"),
    scheduledTime: "10:00",
    totalAmount: 450,
    serviceFee: 54,
    category: "Maler",
    address: {
      street: "Gartenweg",
      houseNumber: "7",
      plz: "10405",
      city: "Berlin",
    },
    photos: ["/placeholder.svg?height=300&width=400", "/placeholder.svg?height=300&width=400"],
    hasReview: false,
  },
  "booking-completed-reviewed": {
    id: "booking-completed-reviewed",
    jobTitle: "Trockenbau - Rigipswand",
    description: "Errichten einer Trennwand aus Rigips im Kinderzimmer. Maße: 3m x 2,5m.",
    providerId: "provider-4",
    providerName: "Stefan Hoffmann",
    providerAvatar: "/placeholder.svg?height=64&width=64",
    providerRating: 4.6,
    providerReviewCount: 78,
    verified: true,
    customerId: "customer-1",
    customerName: "Max Mustermann",
    status: "completed",
    scheduledDate: new Date("2024-01-05"),
    scheduledTime: "08:00",
    totalAmount: 680,
    serviceFee: 81.6,
    category: "Trockenbau",
    address: {
      street: "Lindenallee",
      houseNumber: "23",
      plz: "10719",
      city: "Berlin",
    },
    photos: [],
    hasReview: true,
  },
}

export const mockBookingMessages: Message[] = [
  {
    id: "msg-1",
    senderId: "provider-1",
    senderName: "Klaus Müller",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Guten Tag! Ich komme wie vereinbart am Montag um 9 Uhr. Soll ich Werkzeug mitbringen?",
    timestamp: new Date("2024-01-28T10:30:00"),
    isCurrentUser: false,
  },
  {
    id: "msg-2",
    senderId: "customer-1",
    senderName: "Max Mustermann",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Ja, bitte alles mitbringen. Der Schlüssel liegt beim Nachbarn bereit.",
    timestamp: new Date("2024-01-28T11:15:00"),
    isCurrentUser: true,
  },
  {
    id: "msg-3",
    senderId: "provider-1",
    senderName: "Klaus Müller",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Super, dann ist alles klar. Bis Montag!",
    timestamp: new Date("2024-01-28T11:20:00"),
    isCurrentUser: false,
  },
  {
    id: "msg-4",
    senderId: "customer-1",
    senderName: "Max Mustermann",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Perfekt, danke! Bis dann.",
    timestamp: new Date("2024-01-28T11:22:00"),
    isCurrentUser: true,
  },
]

export const mockProviderStats: ProviderStats = {
  newRequests: 3,
  jobsThisWeek: 5,
  revenue30Days: 4250,
  rating: 4.8,
  reviewCount: 127,
  newJobBoardListings: 12,
}

export const mockProviderBookingRequests: ProviderBookingRequest[] = [
  {
    id: "req-1",
    jobTitle: "Badezimmer Fliesen erneuern",
    customerId: "customer-1",
    customerName: "Anna Bauer",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Fliesen",
    scheduledDate: new Date("2024-02-15"),
    scheduledTime: "10:00",
    address: "Friedrichstraße 123, 10117 Berlin",
    amount: 1850,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    id: "req-2",
    jobTitle: "Elektroinstallation Küche",
    customerId: "customer-2",
    customerName: "Peter Wagner",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Elektrik",
    scheduledDate: new Date("2024-02-18"),
    scheduledTime: "14:00",
    address: "Alexanderplatz 5, 10178 Berlin",
    amount: 320,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
  },
  {
    id: "req-3",
    jobTitle: "Wohnzimmer streichen",
    customerId: "customer-3",
    customerName: "Julia Schneider",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Maler",
    scheduledDate: new Date("2024-02-20"),
    scheduledTime: "09:00",
    address: "Unter den Linden 77, 10117 Berlin",
    amount: 580,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
  },
]

export const mockJobBoardListings: JobBoardListing[] = [
  {
    id: "jb-1",
    title: "Küche renovieren - Fliesen und Arbeitsplatte",
    category: "Fliesen",
    location: "Berlin Mitte",
    plz: "10117",
    budget: 3500,
    urgency: "normal",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    offerCount: 3,
  },
  {
    id: "jb-2",
    title: "Dringende Heizungsreparatur",
    category: "Heizung",
    location: "Berlin Kreuzberg",
    plz: "10965",
    budget: 500,
    urgency: "urgent",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    offerCount: 8,
  },
  {
    id: "jb-3",
    title: "Steckdosen im Wohnzimmer installieren",
    category: "Elektrik",
    location: "Berlin Prenzlauer Berg",
    plz: "10435",
    budget: null,
    urgency: "flexible",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    offerCount: 2,
  },
  {
    id: "jb-4",
    title: "Bad komplett renovieren",
    category: "Sanitär",
    location: "Berlin Charlottenburg",
    plz: "10623",
    budget: 8000,
    urgency: "normal",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    offerCount: 5,
  },
  {
    id: "jb-5",
    title: "Trockenbau Dachgeschoss",
    category: "Trockenbau",
    location: "Berlin Pankow",
    plz: "13187",
    budget: 4500,
    urgency: "flexible",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    offerCount: 1,
  },
]

export const mockJobBoardItems: JobBoardItem[] = [
  {
    id: "jb-1",
    title: "Badezimmer komplett renovieren",
    category: "Sanitär",
    description: "Komplette Badezimmerrenovierung inkl. Fliesen, Sanitär und neuer Dusche. Altbau, ca. 8 qm.",
    location: "Berlin Kreuzberg",
    plz: "10997",
    budget: 8000,
    budgetMax: 12000,
    urgency: "normal",
    timeframe: "7_days",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    offerCount: 3,
    status: "open",
    customerName: "Sandra K.",
  },
  {
    id: "jb-2",
    title: "Dringende Heizungsreparatur - Heizung ausgefallen",
    category: "Heizung",
    description: "Heizung funktioniert nicht mehr seit gestern. Brauche dringend Hilfe, da es sehr kalt ist.",
    location: "Berlin Mitte",
    plz: "10115",
    budget: 500,
    urgency: "urgent",
    timeframe: "asap",
    createdAt: new Date(Date.now() - 30 * 60 * 1000), // 30 min ago
    offerCount: 7,
    status: "open",
    customerName: "Michael B.",
  },
  {
    id: "jb-3",
    title: "Elektroinstallation für neue Küche",
    category: "Elektrik",
    description: "Neue Steckdosen und Anschlüsse für Einbauküche. Herd, Backofen, Spülmaschine, Kühlschrank.",
    location: "Berlin Prenzlauer Berg",
    plz: "10405",
    budget: 1200,
    budgetMax: 1800,
    urgency: "normal",
    timeframe: "7_days",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    offerCount: 5,
    status: "open",
    customerName: "Lisa M.",
  },
  {
    id: "jb-4",
    title: "Wohnzimmer streichen - 35 qm",
    category: "Maler",
    description: "Wände und Decke in Wohnzimmer neu streichen. Farbe wird gestellt. Keine Tapete, direkt auf Putz.",
    location: "Hamburg Altona",
    plz: "22765",
    budget: 600,
    urgency: "flexible",
    timeframe: "custom",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
    offerCount: 8,
    status: "open",
    customerName: "Thomas R.",
  },
  {
    id: "jb-5",
    title: "Trockenbau - Raumteiler einziehen",
    category: "Trockenbau",
    description: "Raumteiler aus Gipskarton mit Tür. Länge ca. 4m, Höhe 2,60m. Schallschutz erwünscht.",
    location: "München Schwabing",
    plz: "80801",
    budget: 2500,
    budgetMax: 3500,
    urgency: "normal",
    timeframe: "7_days",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8 hours ago
    offerCount: 2,
    status: "open",
    customerName: "Julia S.",
  },
  {
    id: "jb-6",
    title: "Wasserhahn tropft - schnelle Reparatur",
    category: "Sanitär",
    description: "Wasserhahn in der Küche tropft seit einer Woche. Vermutlich nur Dichtung.",
    location: "Berlin Charlottenburg",
    plz: "10627",
    budget: null,
    urgency: "normal",
    timeframe: "7_days",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000), // 3 hours ago
    offerCount: 4,
    status: "open",
    customerName: "Andreas H.",
  },
  {
    id: "jb-7",
    title: "Fenster austauschen - Altbau",
    category: "Fenster & Türen",
    description: "3 alte Holzfenster gegen neue Kunststofffenster austauschen. Altbau, denkmalgeschützt.",
    location: "Köln Ehrenfeld",
    plz: "50823",
    budget: 4000,
    budgetMax: 6000,
    urgency: "flexible",
    timeframe: "custom",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    offerCount: 1,
    status: "open",
    customerName: "Petra W.",
  },
  {
    id: "jb-8",
    title: "Fliesenleger für Balkon gesucht",
    category: "Fliesen",
    description: "Balkon ca. 6 qm neu fliesen. Frostsichere Fliesen erforderlich. Material wird gestellt.",
    location: "Berlin Friedrichshain",
    plz: "10243",
    budget: 800,
    budgetMax: 1200,
    urgency: "normal",
    timeframe: "7_days",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
    offerCount: 6,
    status: "open",
    customerName: "Markus L.",
  },
  {
    id: "jb-9",
    title: "DRINGEND: Rohrbruch im Keller",
    category: "Sanitär",
    description: "Rohrbruch im Keller, Wasser läuft. Brauche sofort einen Klempner!",
    location: "Berlin Neukölln",
    plz: "12047",
    budget: null,
    urgency: "urgent",
    timeframe: "asap",
    createdAt: new Date(Date.now() - 15 * 60 * 1000), // 15 min ago
    offerCount: 2,
    status: "open",
    customerName: "Sabine K.",
  },
  {
    id: "jb-10",
    title: "Laminat verlegen - 45 qm",
    category: "Boden",
    description: "Laminat in Wohnung verlegen. Alten Teppich entfernen. Material vorhanden.",
    location: "Hamburg Wandsbek",
    plz: "22041",
    budget: 1500,
    urgency: "flexible",
    timeframe: "custom",
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000), // 18 hours ago
    offerCount: 9,
    status: "open",
    customerName: "Frank D.",
  },
  {
    id: "jb-11",
    title: "Einbauküche montieren",
    category: "Möbelmontage",
    description: "IKEA Küche montieren inkl. Elektro- und Wasseranschluss. Küche bereits geliefert.",
    location: "Berlin Wedding",
    plz: "13353",
    budget: 800,
    budgetMax: 1200,
    urgency: "normal",
    timeframe: "7_days",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    offerCount: 4,
    status: "open",
    customerName: "Nina P.",
  },
  {
    id: "jb-12",
    title: "Gartenzaun erneuern",
    category: "Garten & Außen",
    description: "Alter Holzzaun (ca. 15m) abreißen und neuen Zaun setzen. Material kann gestellt werden.",
    location: "München Pasing",
    plz: "81241",
    budget: 2000,
    budgetMax: 3000,
    urgency: "flexible",
    timeframe: "custom",
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000), // 1.5 days ago
    offerCount: 3,
    status: "open",
    customerName: "Stefan M.",
  },
]

export const mockOnboardingTasks: OnboardingTask[] = [
  {
    id: "task-1",
    label: "Profil vervollständigen",
    completed: true,
    href: "/provider/profil",
  },
  {
    id: "task-2",
    label: "Verifizierung einreichen",
    completed: false,
    href: "/provider/verifizierung",
  },
  {
    id: "task-3",
    label: "Erste Leistung anlegen",
    completed: false,
    href: "/provider/leistungen/neu",
  },
]

export const mockProviderListings: ProviderListing[] = [
  {
    id: "pl-1",
    title: "Badezimmerrenovierung - Komplettservice",
    description: "Professionelle Renovierung Ihres Badezimmers inkl. Fliesen, Sanitär und Elektrik",
    category: "Sanitär",
    price: 2500,
    priceUnit: "Projekt",
    imageUrl: "/placeholder.svg?height=200&width=300",
    isActive: true,
    bookingsCount: 24,
    createdAt: new Date("2023-06-15"),
  },
  {
    id: "pl-2",
    title: "Elektroinstallation Neubau",
    description: "Komplette Elektroinstallation für Neubauten und Sanierungen",
    category: "Elektrik",
    price: 85,
    priceUnit: "Stunde",
    imageUrl: "/placeholder.svg?height=200&width=300",
    isActive: true,
    bookingsCount: 18,
    createdAt: new Date("2023-08-20"),
  },
  {
    id: "pl-3",
    title: "Notfall-Reparatur Elektrik",
    description: "24/7 Notfall-Service für elektrische Probleme und Ausfälle",
    category: "Elektrik",
    price: 120,
    priceUnit: "Stunde",
    imageUrl: "/placeholder.svg?height=200&width=300",
    isActive: false,
    bookingsCount: 7,
    createdAt: new Date("2023-11-05"),
  },
  {
    id: "pl-4",
    title: "Küchenmontage inkl. Anschlüsse",
    description: "Montage von Einbauküchen mit Wasser- und Elektroanschlüssen",
    category: "Montage",
    price: 450,
    priceUnit: "Küche",
    imageUrl: "/placeholder.svg?height=200&width=300",
    isActive: true,
    bookingsCount: 12,
    createdAt: new Date("2023-09-10"),
  },
  {
    id: "pl-5",
    title: "Smart Home Installation",
    description: "Einrichtung und Installation von Smart Home Systemen",
    category: "Elektrik",
    price: 75,
    priceUnit: "Stunde",
    imageUrl: "/placeholder.svg?height=200&width=300",
    isActive: true,
    bookingsCount: 31,
    createdAt: new Date("2024-01-02"),
  },
]

export const mockProviderListingDetail: ProviderListingDetail = {
  id: "listing-1",
  title: "Badezimmerrenovierung - Komplettservice",
  description:
    "Professionelle Renovierung Ihres Badezimmers. Wir übernehmen alle Arbeiten von der Planung bis zur Fertigstellung. Inklusive Fliesenarbeiten, Sanitärinstallation und Elektrik. Hochwertige Materialien und saubere Ausführung garantiert.",
  category: "sanitaer",
  price: 2500,
  priceUnit: "Projekt",
  priceType: "fixed",
  city: "berlin",
  plz: "10115",
  radius: 25,
  photos: [
    "/placeholder.svg?height=400&width=600",
    "/placeholder.svg?height=400&width=600",
    "/placeholder.svg?height=400&width=600",
  ],
  imageUrl: "/placeholder.svg?height=400&width=600",
  isActive: true,
  bookingsCount: 12,
  createdAt: new Date("2024-01-10"),
}

export const mockProviderJobs: ProviderJob[] = [
  {
    id: "pjob-1",
    jobTitle: "Badezimmerrenovierung komplett",
    customerId: "customer-1",
    customerName: "Anna Bauer",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Sanitär",
    status: "requested",
    requestedDate: new Date("2024-02-15"),
    requestedTime: "09:00",
    amount: 2800,
    city: "Berlin",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "pjob-2",
    jobTitle: "Elektroinstallation Küche",
    customerId: "customer-2",
    customerName: "Peter Wagner",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Elektrik",
    status: "payment_pending",
    requestedDate: new Date("2024-02-10"),
    requestedTime: "14:00",
    amount: 450,
    city: "Berlin",
    createdAt: new Date("2024-01-18"),
  },
  {
    id: "pjob-3",
    jobTitle: "Wohnzimmer streichen",
    customerId: "customer-3",
    customerName: "Julia Schneider",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Maler",
    status: "scheduled",
    requestedDate: new Date("2024-02-20"),
    requestedTime: "10:00",
    amount: 680,
    city: "Hamburg",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "pjob-4",
    jobTitle: "Heizungsreparatur",
    customerId: "customer-4",
    customerName: "Markus Fischer",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Heizung",
    status: "in_progress",
    requestedDate: new Date("2024-02-05"),
    requestedTime: "08:00",
    amount: 320,
    city: "München",
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "pjob-5",
    jobTitle: "Trockenbauwand einziehen",
    customerId: "customer-5",
    customerName: "Sandra Meyer",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Trockenbau",
    status: "completed",
    requestedDate: new Date("2024-01-25"),
    requestedTime: "09:00",
    amount: 1200,
    city: "Berlin",
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "pjob-6",
    jobTitle: "Fliesenarbeiten Bad",
    customerId: "customer-6",
    customerName: "Lisa Braun",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Fliesen",
    status: "requested",
    requestedDate: new Date("2024-02-18"),
    requestedTime: "11:00",
    amount: 1850,
    city: "Köln",
    createdAt: new Date("2024-01-22"),
  },
  {
    id: "pjob-7",
    jobTitle: "Küchenmontage",
    customerId: "customer-7",
    customerName: "Lisa Braun",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Montage",
    status: "scheduled",
    requestedDate: new Date("2024-02-22"),
    requestedTime: "08:30",
    amount: 550,
    city: "Berlin",
    createdAt: new Date("2024-01-19"),
  },
  {
    id: "pjob-8",
    jobTitle: "Gartenzaun reparieren",
    customerId: "customer-8",
    customerName: "Hans Richter",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Garten & Außen",
    status: "completed",
    requestedDate: new Date("2024-01-20"),
    requestedTime: "10:00",
    amount: 380,
    city: "Hamburg",
    createdAt: new Date("2024-01-08"),
  },
  {
    id: "pjob-9",
    jobTitle: "Dachrinne reinigen",
    customerId: "customer-9",
    customerName: "Monika Klein",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Dach",
    status: "payment_pending",
    requestedDate: new Date("2024-02-12"),
    requestedTime: "09:00",
    amount: 180,
    city: "München",
    createdAt: new Date("2024-01-21"),
  },
  {
    id: "pjob-10",
    jobTitle: "Fenster abdichten",
    customerId: "customer-10",
    customerName: "Stefan Wolf",
    customerAvatar: "/placeholder.svg?height=40&width=40",
    category: "Fenster & Türen",
    status: "in_progress",
    requestedDate: new Date("2024-02-08"),
    requestedTime: "13:00",
    amount: 240,
    city: "Köln",
    createdAt: new Date("2024-01-17"),
  },
]

export const mockProviderMessages: Message[] = [
  {
    id: "pmsg-1",
    senderId: "customer-1",
    senderName: "Anna Bauer",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Hallo! Ich freue mich auf die Renovierung. Haben Sie noch Fragen zu den Anforderungen?",
    timestamp: new Date("2024-01-20T09:00:00"),
    isCurrentUser: false,
  },
  {
    id: "pmsg-2",
    senderId: "provider-1",
    senderName: "Klaus Müller",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Guten Tag Frau Bauer! Ja, könnten Sie mir bitte die genauen Maße der Duschkabine mitteilen?",
    timestamp: new Date("2024-01-20T10:15:00"),
    isCurrentUser: true,
  },
  {
    id: "pmsg-3",
    senderId: "customer-1",
    senderName: "Anna Bauer",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Die Duschkabine sollte 90x90 cm sein. Passt das?",
    timestamp: new Date("2024-01-20T10:30:00"),
    isCurrentUser: false,
  },
  {
    id: "pmsg-4",
    senderId: "provider-1",
    senderName: "Klaus Müller",
    senderAvatar: "/placeholder.svg?height=40&width=40",
    content: "Perfekt, das passt sehr gut. Ich werde die passenden Materialien besorgen.",
    timestamp: new Date("2024-01-20T10:45:00"),
    isCurrentUser: true,
  },
]

export const mockProviderWorkRequestDetails: Record<string, ProviderWorkRequestDetail> = {
  "work-request-1": {
    id: "work-request-1",
    title: "Küche renovieren - Fliesen und Arbeitsplatte",
    category: "Fliesen",
    description:
      "Suche Handwerker für Fliesenarbeiten in der Küche und Installation einer neuen Arbeitsplatte. Ca. 15 qm Fläche. Die alten Fliesen müssen entfernt und neue verlegt werden. Arbeitsplatte soll aus Granit sein.",
    location: "Berlin Mitte",
    plz: "10115",
    budget: 3500,
    budgetMax: 4500,
    urgency: "normal",
    timeframe: "Innerhalb der nächsten 2 Wochen",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    offerCount: 5,
    status: "open",
    photos: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    accessNotes: "Bitte vorher anrufen. Klingel bei Schmidt.",
    customer: {
      id: "customer-1",
      firstName: "Anna",
      area: "Berlin Mitte",
      memberSince: new Date("2023-06-15"),
    },
    myOffer: undefined,
  },
  "work-request-2": {
    id: "work-request-2",
    title: "Dringende Heizungsreparatur",
    category: "Heizung",
    description:
      "Heizung funktioniert nicht mehr. Brauche dringend Hilfe, da es sehr kalt ist. Die Heizung macht komische Geräusche und wird nicht warm. Thermostat zeigt Fehlercode an.",
    location: "Berlin Kreuzberg",
    plz: "10969",
    budget: 500,
    urgency: "urgent",
    timeframe: "So schnell wie möglich",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    offerCount: 8,
    status: "open",
    photos: ["/placeholder.svg?height=400&width=600"],
    customer: {
      id: "customer-2",
      firstName: "Peter",
      area: "Berlin Kreuzberg",
      memberSince: new Date("2024-01-10"),
    },
    myOffer: undefined,
  },
  "work-request-in-discussion": {
    id: "work-request-in-discussion",
    title: "Badezimmer komplett renovieren",
    category: "Sanitär",
    description:
      "Komplette Badsanierung inkl. Fliesen, Sanitärobjekte und Elektrik. Das Bad ist ca. 8 qm groß. Dusche soll durch bodengleiche Variante ersetzt werden.",
    location: "Berlin Prenzlauer Berg",
    plz: "10405",
    budget: 8000,
    budgetMax: 12000,
    urgency: "flexible",
    timeframe: "Flexible - innerhalb der nächsten 2 Monate",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    offerCount: 12,
    status: "in_discussion",
    photos: ["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"],
    accessNotes: "Schlüssel beim Nachbarn (Wohnung 3B).",
    customer: {
      id: "customer-3",
      firstName: "Julia",
      area: "Berlin Prenzlauer Berg",
      memberSince: new Date("2022-11-20"),
    },
    myOffer: {
      id: "my-offer-1",
      amount: 9500,
      message:
        "Guten Tag Frau Julia! Vielen Dank für Ihre Anfrage. Ich habe mir die Fotos angeschaut. Haben Sie schon eine Vorstellung, welche Fliesen Sie möchten?",
      availableDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      sentAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      status: "pending",
    },
  },
  "work-request-closed": {
    id: "work-request-closed",
    title: "Malerarbeiten Wohnzimmer",
    category: "Maler",
    description: "Wohnzimmer streichen in hellem Grau. Ca. 35 qm Wandfläche. Decke soll weiß bleiben.",
    location: "Berlin Charlottenburg",
    plz: "10627",
    budget: 600,
    urgency: "normal",
    timeframe: "Diese Woche",
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    offerCount: 6,
    status: "closed",
    photos: ["/placeholder.svg?height=400&width=600"],
    customer: {
      id: "customer-4",
      firstName: "Michael",
      area: "Berlin Charlottenburg",
      memberSince: new Date("2023-03-01"),
    },
    myOffer: undefined,
  },
}

export const mockProviderWorkRequestMessages: Record<string, Message[]> = {
  "work-request-1": [],
  "work-request-2": [],
  "work-request-in-discussion": [
    {
      id: "msg-wr-1",
      senderId: "provider-current",
      senderName: "Klaus Müller",
      senderAvatar: "/placeholder.svg?height=40&width=40",
      content:
        "Guten Tag Frau Julia! Vielen Dank für Ihre Anfrage. Ich habe mir die Fotos angeschaut. Haben Sie schon eine Vorstellung, welche Fliesen Sie möchten?",
      timestamp: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000),
      isCurrentUser: true,
    },
    {
      id: "msg-wr-2",
      senderId: "customer-3",
      senderName: "Julia",
      senderAvatar: "/placeholder.svg?height=40&width=40",
      content:
        "Hallo Herr Müller! Ja, ich hätte gerne große Feinsteinzeug-Fliesen in einem hellen Grauton. Können Sie mir dazu beraten?",
      timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      isCurrentUser: false,
    },
    {
      id: "msg-wr-3",
      senderId: "provider-current",
      senderName: "Klaus Müller",
      senderAvatar: "/placeholder.svg?height=40&width=40",
      content:
        "Natürlich! Ich arbeite mit einem Fliesenhändler zusammen, der sehr gute Qualität zu fairen Preisen anbietet. Ich kann Ihnen gerne Muster zeigen bei einem Vor-Ort-Termin.",
      timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000),
      isCurrentUser: true,
    },
  ],
  "work-request-closed": [],
}

// Mock data for Earnings and Transactions
export const mockEarningsSummary: EarningsSummary = {
  totalRevenue: 15750.5,
  totalPayouts: 12300.75,
  pendingBalance: 3449.75,
  averageDailyRevenue: 157.5,
  averageWeeklyRevenue: 1102.5,
  averageMonthlyRevenue: 4725.15,
}

export const mockTransactions: Transaction[] = [
  {
    id: "txn-1",
    date: new Date("2024-02-20"),
    description: "Payment for completed job: Badezimmerrenovierung",
    amount: 2800.0,
    type: "credit",
    status: "completed",
  },
  {
    id: "txn-2",
    date: new Date("2024-02-18"),
    description: "Service fee for booking ID: booking-1",
    amount: -336.0,
    type: "fee",
    status: "completed",
  },
  {
    id: "txn-3",
    date: new Date("2024-02-15"),
    description: "Payout to bank account",
    amount: -2000.0,
    type: "debit",
    status: "processing",
  },
  {
    id: "txn-4",
    date: new Date("2024-02-10"),
    description: "Payment for completed job: Elektroinstallation Küche",
    amount: 450.0,
    type: "credit",
    status: "completed",
  },
  {
    id: "txn-5",
    date: new Date("2024-02-05"),
    description: "Service fee for booking ID: job-detail-2",
    amount: -54.0,
    type: "fee",
    status: "completed",
  },
  {
    id: "txn-6",
    date: new Date("2024-01-25"),
    description: "Payment for completed job: Wohnzimmer streichen",
    amount: 680.0,
    type: "credit",
    status: "completed",
  },
  {
    id: "txn-7",
    date: new Date("2024-01-20"),
    description: "Refund for cancelled service",
    amount: -150.0,
    type: "refund",
    status: "completed",
  },
]
